// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

type EntEnumログ区分 struct {
	Get区分 Enumログ区分 `json:"区分"`
	Get名称 string   `json:"名称"`
}

func NewEntEnumログ区分(区分 Enumログ区分, 名称 string) (*EntEnumログ区分, error) {
	e := &EntEnumログ区分{
		Get区分: 区分,
		Get名称: 名称,
	}
	err := e.Validate()
	return e, err
}
