// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

type EntEnum受払区分 struct {
	Get受払区分  Enum受払区分 `json:"受払区分"`
	Get名称    string   `json:"名称"`
	Get受入フラグ bool     `json:"受入フラグ"`
	Get符号    int      `json:"符号"`
}

func NewEntEnum受払区分(受払区分 Enum受払区分, 名称 string, 受入フラグ bool, 符号 int) (*EntEnum受払区分, error) {
	e := &EntEnum受払区分{
		Get受入フラグ: 受入フラグ,
		Get受払区分:  受払区分,
		Get名称:    名称,
		Get符号:    符号,
	}
	err := e.Validate()
	return e, err
}
