// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

import "time"

type Entgorpmigrations struct {
	Getid         string    `json:"id"`
	Getapplied_at time.Time `json:"applied_at"`
}

func NewEntgorpmigrations(id string, applied_at time.Time) (*Entgorpmigrations, error) {
	e := &Entgorpmigrations{
		Getapplied_at: applied_at,
		Getid:         id,
	}
	err := e.Validate()
	return e, err
}
