// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

import "time"

type Valgorpmigrations struct {
	Getid         string    `json:"id"`
	Getapplied_at time.Time `json:"applied_at"`
}

func NewValgorpmigrations(id string, applied_at time.Time) (*Valgorpmigrations, error) {
	v := &Valgorpmigrations{
		Getapplied_at: applied_at,
		Getid:         id,
	}
	err := v.Validate()
	return v, err
}
