// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

import types "techbookfest16-sample/domain/types"

type Entリソース変更履歴アップロード時 struct {
	*Entリソース変更履歴  `json:"リソース変更履歴,omitempty"`
	Getアップロード履歴ID types.No `json:"アップロード履歴ID"`
}

func NewEntリソース変更履歴アップロード時(リソース変更履歴 *Entリソース変更履歴, アップロード履歴ID types.No) (*Entリソース変更履歴アップロード時, error) {
	e := &Entリソース変更履歴アップロード時{
		Entリソース変更履歴:   リソース変更履歴,
		Getアップロード履歴ID: アップロード履歴ID,
	}
	err := e.Validate()
	return e, err
}
