// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

type Valリソース変更履歴アップロード時 struct {
	Getアップロード履歴ID No `json:"アップロード履歴ID"`
}

func NewValリソース変更履歴アップロード時(アップロード履歴ID No) (*Valリソース変更履歴アップロード時, error) {
	v := &Valリソース変更履歴アップロード時{Getアップロード履歴ID: アップロード履歴ID}
	err := v.Validate()
	return v, err
}
