// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

import types "techbookfest16-sample/domain/types"

type Valログアップロード時 struct {
	Getアップロード履歴ID types.No `json:"アップロード履歴ID"`
}

func NewValログアップロード時(アップロード履歴ID types.No) (*Valログアップロード時, error) {
	v := &Valログアップロード時{Getアップロード履歴ID: アップロード履歴ID}
	err := v.Validate()
	return v, err
}
