// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

import types "techbookfest16-sample/domain/types"

type Entログアップロード時 struct {
	*Entログ        `json:"ログ,omitempty"`
	Getアップロード履歴ID types.No `json:"アップロード履歴ID"`
}

func NewEntログアップロード時(ログ *Entログ, アップロード履歴ID types.No) (*Entログアップロード時, error) {
	e := &Entログアップロード時{
		Entログ:         ログ,
		Getアップロード履歴ID: アップロード履歴ID,
	}
	err := e.Validate()
	return e, err
}
