// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

import types "techbookfest16-sample/domain/types"

type Entログ画面操作時 struct {
	*Entログ      `json:"ログ,omitempty"`
	Get操作ユーザーID types.No `json:"操作ユーザーID"`
}

func NewEntログ画面操作時(ログ *Entログ, 操作ユーザーID types.No) (*Entログ画面操作時, error) {
	e := &Entログ画面操作時{
		Entログ:       ログ,
		Get操作ユーザーID: 操作ユーザーID,
	}
	err := e.Validate()
	return e, err
}
