// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

import types "techbookfest16-sample/domain/types"

type Rep単位 interface {
	List() ([]*Ent単位, error)
	GetBy(types.Code単位) (*Ent単位, error)
	AddNew(*Ent単位) error
	Save(No) error
}
