// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

import types "techbookfest16-sample/domain/types"

type Ent単位 struct {
	Getコード types.Code単位 `json:"コード"`
	Get名称  string       `json:"名称"`
}

func NewEnt単位(コード types.Code単位, 名称 string) (*Ent単位, error) {
	e := &Ent単位{
		Getコード: コード,
		Get名称:  名称,
	}
	err := e.Validate()
	return e, err
}
func (e *Ent単位) Id() types.Code単位 {
	return e.Getコード
}
func (e *Ent単位) Equals(other types.Identifier[types.Code単位]) bool {
	if other == nil {
		return false
	}
	if other.Equals(e) {
		return true
	}
	return false
}
