// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

import types "techbookfest16-sample/domain/types"

type Val受払仕入 struct {
	Get仕入数量 types.Quantity `json:"仕入数量"`
	Get仕入金額 types.Amount   `json:"仕入金額"`
	Get仕入単価 types.Price    `json:"仕入単価"`
}

func NewVal受払仕入(仕入数量 types.Quantity, 仕入金額 types.Amount, 仕入単価 types.Price) (*Val受払仕入, error) {
	v := &Val受払仕入{
		Get仕入単価: 仕入単価,
		Get仕入数量: 仕入数量,
		Get仕入金額: 仕入金額,
	}
	err := v.Validate()
	return v, err
}
