// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

import types "techbookfest16-sample/domain/types"

type Val受払出荷 struct {
	Get出荷数量 types.Quantity `json:"出荷数量"`
}

func NewVal受払出荷(出荷数量 types.Quantity) (*Val受払出荷, error) {
	v := &Val受払出荷{Get出荷数量: 出荷数量}
	err := v.Validate()
	return v, err
}
