// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

import types "techbookfest16-sample/domain/types"

type Ent受払出荷 struct {
	*Ent受払  `json:"受払,omitempty"`
	Get出荷数量 types.Quantity `json:"出荷数量"`
}

func NewEnt受払出荷(受払 *Ent受払, 出荷数量 types.Quantity) (*Ent受払出荷, error) {
	e := &Ent受払出荷{
		Ent受払:   受払,
		Get出荷数量: 出荷数量,
	}
	err := e.Validate()
	return e, err
}
