// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

import types "techbookfest16-sample/domain/types"

type Val受払投入実績 struct {
	Get投入数量   types.Quantity `json:"投入数量"`
	Get製造指図ID No             `json:"製造指図ID"`
}

func NewVal受払投入実績(投入数量 types.Quantity, 製造指図ID No) (*Val受払投入実績, error) {
	v := &Val受払投入実績{
		Get投入数量:   投入数量,
		Get製造指図ID: 製造指図ID,
	}
	err := v.Validate()
	return v, err
}
