// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

import types "techbookfest16-sample/domain/types"

type Val品目仕入品 struct {
	Get標準単価 types.Price `json:"標準単価"`
}

func NewVal品目仕入品(標準単価 types.Price) (*Val品目仕入品, error) {
	v := &Val品目仕入品{Get標準単価: 標準単価}
	err := v.Validate()
	return v, err
}
