// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

import types "techbookfest16-sample/domain/types"

type Ent品目 struct {
	Getコード     types.Code品目 `json:"コード"`
	Get名称      string       `json:"名称"`
	Get基準単位    *Ent単位       `json:"基準単位,omitempty"`
	Get生産用品目区分 *Ent生産用品目区分  `json:"生産用品目区分,omitempty"`
}

func NewEnt品目(コード types.Code品目, 名称 string, 基準単位 *Ent単位, 生産用品目区分 *Ent生産用品目区分) (*Ent品目, error) {
	e := &Ent品目{
		Getコード:     コード,
		Get名称:      名称,
		Get基準単位:    基準単位,
		Get生産用品目区分: 生産用品目区分,
	}
	err := e.Validate()
	return e, err
}
