// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

type Val品目製造品 struct {
	GetMRP計算対象フラグ bool `json:"MRP計算対象フラグ"`
}

func NewVal品目製造品(MRP計算対象フラグ bool) (*Val品目製造品, error) {
	v := &Val品目製造品{GetMRP計算対象フラグ: MRP計算対象フラグ}
	err := v.Validate()
	return v, err
}
