// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

import types "techbookfest16-sample/domain/types"

type Rep品目 interface {
	Get品目一覧() ([]*Ent品目, error)
	Get仕入品一覧() ([]*Ent品目仕入品, error)
	Get品目By(types.Code品目) (*Ent品目, error)
	Get仕入品By(types.Code品目) (*Ent品目仕入品, error)
	AddNew仕入品(*Ent品目仕入品) error
	Save(types.No) error
}
