// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

type Ent品目製造品 struct {
	*Ent品目        `json:"品目,omitempty"`
	GetMRP計算対象フラグ bool `json:"MRP計算対象フラグ"`
}

func NewEnt品目製造品(品目 *Ent品目, MRP計算対象フラグ bool) (*Ent品目製造品, error) {
	e := &Ent品目製造品{
		Ent品目:         品目,
		GetMRP計算対象フラグ: MRP計算対象フラグ,
	}
	err := e.Validate()
	return e, err
}
