// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

import types "techbookfest16-sample/domain/types"

type Ent品目仕入品 struct {
	*Ent品目  `json:"品目,omitempty"`
	Get標準単価 types.Price `json:"標準単価"`
}

func NewEnt品目仕入品(品目 *Ent品目, 標準単価 types.Price) (*Ent品目仕入品, error) {
	e := &Ent品目仕入品{
		Ent品目:   品目,
		Get標準単価: 標準単価,
	}
	err := e.Validate()
	return e, err
}
