// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

import types "techbookfest16-sample/domain/types"

type Ent生産用品目区分 struct {
	Getコード     types.Code生産用品目区分 `json:"コード"`
	Get名称      string            `json:"名称"`
	Get何かのフラグ1 bool              `json:"何かのフラグ1"`
	Get何かのフラグ2 bool              `json:"何かのフラグ2"`
}

func NewEnt生産用品目区分(コード types.Code生産用品目区分, 名称 string, 何かのフラグ1 bool, 何かのフラグ2 bool) (*Ent生産用品目区分, error) {
	e := &Ent生産用品目区分{
		Getコード:     コード,
		Get何かのフラグ1: 何かのフラグ1,
		Get何かのフラグ2: 何かのフラグ2,
		Get名称:      名称,
	}
	err := e.Validate()
	return e, err
}
func (e *Ent生産用品目区分) Id() types.Code生産用品目区分 {
	return e.Getコード
}
func (e *Ent生産用品目区分) Equals(other types.Identifier[types.Code生産用品目区分]) bool {
	if other == nil {
		return false
	}
	if other.Equals(e) {
		return true
	}
	return false
}
