// Code generated by xlsx2go.go; DO NOT EDIT.

package objects

type Rep生産用品目区分 interface {
	List() ([]*Ent生産用品目区分, error)
	GetBy(Code生産用品目区分) (*Ent生産用品目区分, error)
	AddNew(*Ent生産用品目区分) error
	Save(No) error
}
