// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

type tblEnum受払区分 string

func TblEnum受払区分() tblEnum受払区分 {
	return tblEnum受払区分("Enum受払区分")
}

type fldEnum受払区分 string

func (t tblEnum受払区分) Fld受払区分() fldEnum受払区分 {
	return fldEnum受払区分("受払区分")
}
func (t tblEnum受払区分) Fld名称() fldEnum受払区分 {
	return fldEnum受払区分("名称")
}
func (t tblEnum受払区分) Fld受入フラグ() fldEnum受払区分 {
	return fldEnum受払区分("受入フラグ")
}
func (t tblEnum受払区分) Fld符号() fldEnum受払区分 {
	return fldEnum受払区分("符号")
}
