// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import (
	"fmt"
	pq "github.com/lib/pq"
	objects "techbookfest16-sample/domain/objects"
)

type WbEnumログ区分 interface {
	And(field fldEnumログ区分, op whereBuilderOperater, val interface{}) WbEnumログ区分
	Clear()
	Exists(EbEnumログ区分) WbEnumログ区分
	build(argCntStart ...int) (where Where)
}
type wbEnumログ区分 struct {
	config []whereBuilderExp
	ebs    []EbEnumログ区分
}

func NewWbEnumログ区分() WbEnumログ区分 {
	return &wbEnumログ区分{
		config: make([]whereBuilderExp, 0),
		ebs:    make([]EbEnumログ区分, 0),
	}
}
func newWbEnumログ区分WithPrimaryKeys(区分 objects.Enumログ区分) WbEnumログ区分 {
	wb := &wbEnumログ区分{config: make([]whereBuilderExp, 0)}
	wb.And(TblEnumログ区分().Fld区分(), OpEqu, 区分)

	return wb
}
func (wb *wbEnumログ区分) And(field fldEnumログ区分, op whereBuilderOperater, val interface{}) WbEnumログ区分 {
	wb.config = append(wb.config, whereBuilderExp{
		field: string(field),
		op:    op,
		val:   val,
	})
	return wb
}
func (wb *wbEnumログ区分) Clear() {
	wb.config = make([]whereBuilderExp, 0)
}
func (wb *wbEnumログ区分) Exists(eb EbEnumログ区分) WbEnumログ区分 {
	wb.ebs = append(wb.ebs, eb)
	return wb
}
func (wb *wbEnumログ区分) build(argsCntStart ...int) (where Where) {
	where.w = ""
	where.prms = make([]interface{}, 0, len(wb.config))
	if len(argsCntStart) == 1 {
		where.argsCnt = argsCntStart[0]
	}
	for _, e := range wb.config {
		switch e.op {
		case OpIn:
			where.argsCnt++
			where.w += fmt.Sprintf(" AND (\"%s\"%s)", e.field, fmt.Sprintf(e.op.string(), fmt.Sprintf("$%d", where.argsCnt)))
			where.prms = append(where.prms, pq.Array(e.val))
			continue
		case OpIsNull:
			fallthrough
		case OpIsNotNull:
			where.w += fmt.Sprintf(" AND (\"%s\"%s)", e.field, e.op.string())
			continue
		default:
			where.argsCnt++
			where.w += fmt.Sprintf(" AND (\"%s\"%s)", e.field, fmt.Sprintf(e.op.string(), fmt.Sprintf("$%d", where.argsCnt)))
			where.prms = append(where.prms, e.val)
			continue
		}
	}
	for _, eb := range wb.ebs {
		w := eb.buildEbEnumログ区分(where.argsCnt)
		where.Append(w)
	}
	return
}

type nothingWbEnumログ区分 struct{}

func (wb *nothingWbEnumログ区分) And(field fldEnumログ区分, op whereBuilderOperater, val interface{}) WbEnumログ区分 {
	return wb
}
func (wb *nothingWbEnumログ区分) Clear() {}
func (wb *nothingWbEnumログ区分) Exists(_ EbEnumログ区分) WbEnumログ区分 {
	return wb
}
func (wb *nothingWbEnumログ区分) build(argCntStart ...int) (where Where) {
	return Where{w: " AND 1<>1"}
}
func NewNothingWbEnumログ区分() WbEnumログ区分 {
	return &nothingWbEnumログ区分{}
}
