// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

type tblEnumログ区分 string

func TblEnumログ区分() tblEnumログ区分 {
	return tblEnumログ区分("Enumログ区分")
}

type fldEnumログ区分 string

func (t tblEnumログ区分) Fld区分() fldEnumログ区分 {
	return fldEnumログ区分("区分")
}
func (t tblEnumログ区分) Fld名称() fldEnumログ区分 {
	return fldEnumログ区分("名称")
}
