// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import (
	"fmt"
	pq "github.com/lib/pq"
)

type Wbgorpmigrations interface {
	And(field fldgorpmigrations, op whereBuilderOperater, val interface{}) Wbgorpmigrations
	Clear()
	build(argCntStart ...int) (where Where)
}
type wbgorpmigrations struct {
	config []whereBuilderExp
}

func NewWbgorpmigrations() Wbgorpmigrations {
	return &wbgorpmigrations{config: make([]whereBuilderExp, 0)}
}
func newWbgorpmigrationsWithPrimaryKeys(id string) Wbgorpmigrations {
	wb := &wbgorpmigrations{config: make([]whereBuilderExp, 0)}
	wb.And(Tblgorpmigrations().Fldid(), OpEqu, id)

	return wb
}
func (wb *wbgorpmigrations) And(field fldgorpmigrations, op whereBuilderOperater, val interface{}) Wbgorpmigrations {
	wb.config = append(wb.config, whereBuilderExp{
		field: string(field),
		op:    op,
		val:   val,
	})
	return wb
}
func (wb *wbgorpmigrations) Clear() {
	wb.config = make([]whereBuilderExp, 0)
}
func (wb *wbgorpmigrations) build(argCntStart ...int) (where Where) {
	where.w = ""
	where.prms = make([]interface{}, 0, len(wb.config))
	argCnt := 1
	if len(argCntStart) == 1 {
		argCnt = argCntStart[0]
	}
	for _, e := range wb.config {
		switch e.op {
		case OpIn:
			where.w += fmt.Sprintf(" AND (\"%s\"%s)", e.field, fmt.Sprintf(e.op.string(), fmt.Sprintf("$%d", argCnt)))
			argCnt++
			where.prms = append(where.prms, pq.Array(e.val))
			continue
		case OpIsNull:
			fallthrough
		case OpIsNotNull:
			where.w += fmt.Sprintf(" AND (\"%s\"%s)", e.field, e.op.string())
			continue
		default:
			where.w += fmt.Sprintf(" AND (\"%s\"%s)", e.field, fmt.Sprintf(e.op.string(), fmt.Sprintf("$%d", argCnt)))
			argCnt++
			where.prms = append(where.prms, e.val)
			continue
		}
	}
	return
}

type nothingWbgorpmigrations struct{}

func (wb *nothingWbgorpmigrations) And(field fldgorpmigrations, op whereBuilderOperater, val interface{}) Wbgorpmigrations {
	return wb
}
func (wb *nothingWbgorpmigrations) Clear() {}
func (wb *nothingWbgorpmigrations) build(argCntStart ...int) (where Where) {
	return Where{w: " AND 1<>1"}
}
func NewNothingWbgorpmigrations() Wbgorpmigrations {
	return &nothingWbgorpmigrations{}
}
