// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

type tblgorpmigrations string

func Tblgorpmigrations() tblgorpmigrations {
	return tblgorpmigrations("gorp_migrations")
}

type fldgorpmigrations string

func (t tblgorpmigrations) Fldid() fldgorpmigrations {
	return fldgorpmigrations("id")
}
func (t tblgorpmigrations) Fldapplied_at() fldgorpmigrations {
	return fldgorpmigrations("applied_at")
}
