// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

type Dtoリソース変更履歴アップロード時 struct {
	FldID         Id
	Fldアップロード履歴ID Id

	rowState DataRowState
	Ub       *ubリソース変更履歴アップロード時 `json:"-"`
}

func (d Dtoリソース変更履歴アップロード時) TableName() string {
	return "リソース変更履歴_アップロード時"
}
func (d Dtoリソース変更履歴アップロード時) RowState() DataRowState {
	return d.rowState
}

// Import はDtoリソース変更履歴アップロード時型に主キー以外を上書きする。
func (d *Dtoリソース変更履歴アップロード時) Import(アップロード履歴ID Id) {
	// 項目がすべて一致していたら、何もしない
	if d.Fldアップロード履歴ID == アップロード履歴ID {
		return
	}
	if d.Fldアップロード履歴ID != アップロード履歴ID {
		d.Fldアップロード履歴ID = アップロード履歴ID
		d.Ub.Set(Tblリソース変更履歴アップロード時().Fldアップロード履歴ID(), アップロード履歴ID)
	}

}
