// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

type tblリソース変更履歴 string

func Tblリソース変更履歴() tblリソース変更履歴 {
	return tblリソース変更履歴("リソース変更履歴")
}

type fldリソース変更履歴 string

func (t tblリソース変更履歴) FldID() fldリソース変更履歴 {
	return fldリソース変更履歴("ID")
}
func (t tblリソース変更履歴) Fld登録日時() fldリソース変更履歴 {
	return fldリソース変更履歴("登録日時")
}
func (t tblリソース変更履歴) Fldリソース名() fldリソース変更履歴 {
	return fldリソース変更履歴("リソース名")
}
func (t tblリソース変更履歴) Fld変更区分() fldリソース変更履歴 {
	return fldリソース変更履歴("変更区分")
}
func (t tblリソース変更履歴) Fld変更内容() fldリソース変更履歴 {
	return fldリソース変更履歴("変更内容")
}
