// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import (
	"bytes"
	"time"
)

type Dtoリソース変更履歴 struct {
	FldNo    Id
	Fld登録日時  time.Time
	Fldリソース名 string
	Fld変更区分  string
	Fld変更内容  []byte

	rowState DataRowState
	Ub       *ubリソース変更履歴 `json:"-"`
}

func (d Dtoリソース変更履歴) TableName() string {
	return "リソース変更履歴"
}
func (d Dtoリソース変更履歴) RowState() DataRowState {
	return d.rowState
}

// Import はDtoリソース変更履歴型に主キー以外を上書きする。
func (d *Dtoリソース変更履歴) Import(登録日時 time.Time, リソース名 string, 変更区分 string, 変更内容 []byte) {
	// 項目がすべて一致していたら、何もしない
	if d.Fld登録日時 == 登録日時 && d.Fldリソース名 == リソース名 && d.Fld変更区分 == 変更区分 && bytes.Equal(d.Fld変更内容, 変更内容) {
		return
	}
	if d.Fld登録日時 != 登録日時 {
		d.Fld登録日時 = 登録日時
		d.Ub.Set(Tblリソース変更履歴().Fld登録日時(), 登録日時)
	}
	if d.Fldリソース名 != リソース名 {
		d.Fldリソース名 = リソース名
		d.Ub.Set(Tblリソース変更履歴().Fldリソース名(), リソース名)
	}
	if d.Fld変更区分 != 変更区分 {
		d.Fld変更区分 = 変更区分
		d.Ub.Set(Tblリソース変更履歴().Fld変更区分(), 変更区分)
	}
	if !bytes.Equal(d.Fld変更内容, 変更内容) {
		d.Fld変更内容 = 変更内容
		d.Ub.Set(Tblリソース変更履歴().Fld変更内容(), 変更内容)
	}

}
