// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

type tblリソース変更履歴アップロード時 string

func Tblリソース変更履歴アップロード時() tblリソース変更履歴アップロード時 {
	return tblリソース変更履歴アップロード時("リソース変更履歴_アップロード時")
}

type fldリソース変更履歴アップロード時 string

func (t tblリソース変更履歴アップロード時) FldID() fldリソース変更履歴アップロード時 {
	return fldリソース変更履歴アップロード時("ID")
}
func (t tblリソース変更履歴アップロード時) Fldアップロード履歴ID() fldリソース変更履歴アップロード時 {
	return fldリソース変更履歴アップロード時("アップロード履歴ID")
}
