// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import (
	"database/sql"
	"fmt"
	a "github.com/Moiterika/a"
	xerrors "golang.org/x/xerrors"
	"strconv"
	"strings"
	types "techbookfest16-sample/domain/types"
)

type daoTrnリソース変更履歴 struct {
	dm        *DaoTrnManager
	trn       *sql.Tx
	WbForInit Wbリソース変更履歴
}

func (d *daoTrnリソース変更履歴) init() (err error) {
	d.dm.dtリソース変更履歴, err = d.SelectW(d.WbForInit)
	if err != nil {
		return xerrors.Errorf(": %w", err)
	}
	d.dm.mapIDvsDrリソース変更履歴 = a.ToMap(d.dm.dtリソース変更履歴, func(e *Dtoリソース変更履歴) Id {
		return e.FldNo
	})
	return
}
func (d *daoTrnリソース変更履歴) Reset() {
	list := make([]*Dtoリソース変更履歴, 0, len(d.dm.dtリソース変更履歴))
	for _, dr := range d.dm.dtリソース変更履歴 {
		if dr.rowState == Deleted {
			dr.rowState = Detached
			continue
		} else {
			dr.rowState = UnChanged
			list = append(list, dr)
		}
	}
	d.dm.dtリソース変更履歴 = list
}
func (d daoTrnリソース変更履歴) Dt() ([]*Dtoリソース変更履歴, error) {
	if len(d.dm.dtリソース変更履歴) == 0 {
		err := d.init()
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return nil, err
		}
	}
	return d.dm.dtリソース変更履歴, nil
}
func (d daoTrnリソース変更履歴) GetBy(id Id) (dr *Dtoリソース変更履歴, err error) {
	if len(d.dm.mapIDvsDrリソース変更履歴) == 0 {
		err = d.init()
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
	}
	var ok bool
	dr, ok = d.dm.mapIDvsDrリソース変更履歴[id]
	if !ok {
		err = xerrors.Errorf("リソース変更履歴が見つかりません。No=%d: %w", id, types.ErrNotFound)
		return
	}
	return
}
func (d daoTrnリソース変更履歴) SelectAll() ([]*Dtoリソース変更履歴, error) {
	sql := fmt.Sprintf(sqlSelectリソース変更履歴, "")
	rows, err := d.trn.Query(sql)
	if err != nil {
		return nil, xerrors.Errorf("sql=%s: %w", sql, err)
	}
	defer rows.Close()
	var dt []*Dtoリソース変更履歴
	for rows.Next() {
		var dr Dtoリソース変更履歴
		err = rows.Scan(&dr.FldNo, &dr.Fld登録日時, &dr.Fldリソース名, &dr.Fld変更区分, &dr.Fld変更内容)
		if err != nil {
			return nil, xerrors.Errorf(": %w", err)
		}
		dr.rowState = Detached
		dr.Ub = NewUbリソース変更履歴()
		dt = append(dt, &dr)
	}
	return dt, rows.Err()
}
func (d daoTrnリソース変更履歴) SelectW(wb Wbリソース変更履歴) ([]*Dtoリソース変更履歴, error) {
	where := wb.build()
	prms, exists := where.Params()
	if exists {
		sql := fmt.Sprintf(sqlSelectリソース変更履歴, where.String())
		rows, err := d.trn.Query(sql, prms...)
		if err != nil {
			return nil, xerrors.Errorf("sql=%s, args=%v: %w", sql, prms, err)
		}
		defer rows.Close()
		var dt []*Dtoリソース変更履歴
		for rows.Next() {
			var dr Dtoリソース変更履歴
			err = rows.Scan(&dr.FldNo, &dr.Fld登録日時, &dr.Fldリソース名, &dr.Fld変更区分, &dr.Fld変更内容)
			if err != nil {
				return nil, xerrors.Errorf(": %w", err)
			}
			dr.rowState = Detached
			dr.Ub = NewUbリソース変更履歴()
			dt = append(dt, &dr)
		}
		return dt, rows.Err()
	} else {
		return d.SelectAll()
	}
}
func (d daoTrnリソース変更履歴) Count() (cnt int64, err error) {
	return d.CountW(NewWbリソース変更履歴())
}
func (d daoTrnリソース変更履歴) CountW(wb Wbリソース変更履歴) (cnt int64, err error) {
	where := wb.build()
	prms, exists := where.Params()
	if exists {
		err = d.trn.QueryRow(fmt.Sprintf(sqlSelectリソース変更履歴ForAggregation, "count(\"No\")", where.String()), prms...).Scan(&cnt)
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
		return
	} else {
		err = d.trn.QueryRow(fmt.Sprintf(sqlSelectリソース変更履歴ForAggregation, "count(\"No\")", "")).Scan(&cnt)
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
		return
	}
}

// Min はリソース変更履歴のfld最小値を返します。
func (d daoTrnリソース変更履歴) Min(fld fldリソース変更履歴) (min int64, err error) {
	return d.MinW(fld, NewWbリソース変更履歴())
}
func (d daoTrnリソース変更履歴) MinW(fld fldリソース変更履歴, wb Wbリソース変更履歴) (min int64, err error) {
	where := wb.build()
	prms, exists := where.Params()
	var x sql.NullInt64
	if exists {
		err = d.trn.QueryRow(fmt.Sprintf(sqlSelectリソース変更履歴ForAggregation, fmt.Sprintf("min(%s)", strconv.Quote(string(fld))), where.String()), prms...).Scan(&x)
	} else {
		err = d.trn.QueryRow(fmt.Sprintf(sqlSelectリソース変更履歴ForAggregation, fmt.Sprintf("min(%s)", strconv.Quote(string(fld))), where.String())).Scan(&x)
	}
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	if !x.Valid {
		err = xerrors.Errorf(": %w", types.ErrNotFound)
		return
	}
	min = x.Int64
	return
}

// Max はリソース変更履歴のfld最大値を返します。
func (d daoTrnリソース変更履歴) Max(fld fldリソース変更履歴) (max int64, err error) {
	return d.MaxW(fld, NewWbリソース変更履歴())
}
func (d daoTrnリソース変更履歴) MaxW(fld fldリソース変更履歴, wb Wbリソース変更履歴) (max int64, err error) {
	where := wb.build()
	prms, exists := where.Params()
	var x sql.NullInt64
	if exists {
		err = d.trn.QueryRow(fmt.Sprintf(sqlSelectリソース変更履歴ForAggregation, fmt.Sprintf("max(%s)", strconv.Quote(string(fld))), where.String()), prms...).Scan(&x)
	} else {
		err = d.trn.QueryRow(fmt.Sprintf(sqlSelectリソース変更履歴ForAggregation, fmt.Sprintf("max(%s)", strconv.Quote(string(fld))), where.String())).Scan(&x)
	}
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	if !x.Valid {
		err = xerrors.Errorf(": %w", types.ErrNotFound)
		return
	}
	max = x.Int64
	return
}
func (d daoTrnリソース変更履歴) Insert(dr *Dtoリソース変更履歴) (err error) {
	err = d.trn.QueryRow(sqlInsertリソース変更履歴, dr.Fld登録日時, dr.Fldリソース名, dr.Fld変更区分, dr.Fld変更内容).Scan(&dr.FldNo)
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	dr.rowState = Added
	d.dm.dtリソース変更履歴 = append(d.dm.dtリソース変更履歴, dr)
	d.dm.mapIDvsDrリソース変更履歴[dr.FldNo] = dr
	return
}
func (d daoTrnリソース変更履歴) MultiInsert(dt []*Dtoリソース変更履歴) (err error) {
	cs := a.Chunk(dt, 1000)
	for _, c := range cs {
		vals := make([]string, len(c))
		args := make([]interface{}, len(c)*4)
		for i, dr := range c {
			vals[i] = fmt.Sprintf(sqlValue4, 4*i+1, 4*i+2, 4*i+3, 4*i+4)
			args[4*i] = dr.Fld登録日時
			args[4*i+1] = dr.Fldリソース名
			args[4*i+2] = dr.Fld変更区分
			args[4*i+3] = dr.Fld変更内容
			dr.rowState = Added
		}
		_, err = d.trn.Exec(fmt.Sprintf(sqlMultiInsertリソース変更履歴, strings.Join(vals, ",")), args...)
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
	}
	return
}
func (d daoTrnリソース変更履歴) UpdateBy(dr *Dtoリソース変更履歴) (cnt int64, err error) {
	if dr.Ub.Count() == 0 {
		dr.rowState = UnChanged
		return
	}
	s, w, execArgs := dr.Ub.build(newWbリソース変更履歴WithPrimaryKeys(dr.FldNo))
	sql := fmt.Sprintf(sqlUpdateリソース変更履歴, s, w)
	result, err := d.trn.Exec(sql, execArgs...)
	if err != nil {
		err = xerrors.Errorf("sql=%s, args=%v: %w", sql, execArgs, err)
		return
	}
	cnt, err = result.RowsAffected()
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	dr.rowState = Modified
	return
}
func (d daoTrnリソース変更履歴) UpdateW(ub *ubリソース変更履歴, wb Wbリソース変更履歴) (cnt int64, err error) {
	s, w, execArgs := ub.build(wb)
	sql := fmt.Sprintf(sqlUpdateリソース変更履歴, s, w)
	result, err := d.trn.Exec(sql, execArgs...)
	if err != nil {
		err = xerrors.Errorf("sql=%s, args=%v: %w", sql, execArgs, err)
		return
	}
	cnt, err = result.RowsAffected()
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	return
}
func (d daoTrnリソース変更履歴) DeleteBy(dr *Dtoリソース変更履歴) (cnt int64, err error) {
	where := newWbリソース変更履歴WithPrimaryKeys(dr.FldNo).build()
	prms, exists := where.Params()
	if !exists {
		err = xerrors.Errorf("主キーがありません。: %#v", *dr)
		return
	}
	sql := fmt.Sprintf(sqlDeleteリソース変更履歴, where.String())
	result, errExec := d.trn.Exec(sql, prms...)
	if errExec != nil {
		err = xerrors.Errorf("sql=%s, args=%v: %w", sql, prms, errExec)
		return
	}
	cnt, err = result.RowsAffected()
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	dr.rowState = Deleted
	return
}
func (d daoTrnリソース変更履歴) DeleteW(wb Wbリソース変更履歴) (cnt int64, err error) {
	where := wb.build()
	prms, exists := where.Params()
	if exists {
		sql := fmt.Sprintf(sqlDeleteリソース変更履歴, where.String())
		result, errExec := d.trn.Exec(sql, prms...)
		if errExec != nil {
			err = xerrors.Errorf("sql=%s, args=%v: %w", sql, prms, errExec)
			return
		}
		cnt, err = result.RowsAffected()
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
	} else {
		result, errExec := d.trn.Exec(sqlTruncateリソース変更履歴)
		if errExec != nil {
			err = xerrors.Errorf("sql=%s: %w", sqlTruncateリソース変更履歴, errExec)
			return
		}
		cnt, err = result.RowsAffected()
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
	}
	return
}
