// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import "fmt"

type ebリソース変更履歴アップロード時joinリソース変更履歴 struct {
	wb Wbリソース変更履歴
}

func NewEbリソース変更履歴アップロード時joinリソース変更履歴() *ebリソース変更履歴アップロード時joinリソース変更履歴 {
	return &ebリソース変更履歴アップロード時joinリソース変更履歴{wb: NewWbリソース変更履歴()}
}
func (eb *ebリソース変更履歴アップロード時joinリソース変更履歴) And(field fldリソース変更履歴, op whereBuilderOperater, val interface{}) Ebリソース変更履歴アップロード時 {
	eb.wb.And(field, op, val)
	return eb
}
func (eb *ebリソース変更履歴アップロード時joinリソース変更履歴) buildEbリソース変更履歴アップロード時(argCntStart ...int) (where Where) {
	where = eb.wb.build(argCntStart...)
	where.w = fmt.Sprintf(" AND EXISTS (SELECT * FROM \"リソース変更履歴\" WHERE \"リソース変更履歴\".\"No\" = \"リソース変更履歴_アップロード時\".\"No\" %s)", where.w)
	return
}
