// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import (
	"fmt"
	pq "github.com/lib/pq"
)

type Wbログ interface {
	And(field fldログ, op whereBuilderOperater, val interface{}) Wbログ
	Clear()
	build(argCntStart ...int) (where Where)
}
type wbログ struct {
	config []whereBuilderExp
}

func NewWbログ() Wbログ {
	return &wbログ{config: make([]whereBuilderExp, 0)}
}
func newWbログWithPrimaryKeys(ID Id) Wbログ {
	wb := &wbログ{config: make([]whereBuilderExp, 0)}
	wb.And(Tblログ().FldID(), OpEqu, ID)

	return wb
}
func (wb *wbログ) And(field fldログ, op whereBuilderOperater, val interface{}) Wbログ {
	wb.config = append(wb.config, whereBuilderExp{
		field: string(field),
		op:    op,
		val:   val,
	})
	return wb
}
func (wb *wbログ) Clear() {
	wb.config = make([]whereBuilderExp, 0)
}
func (wb *wbログ) build(argCntStart ...int) (where Where) {
	where.w = ""
	where.prms = make([]interface{}, 0, len(wb.config))
	argCnt := 1
	if len(argCntStart) == 1 {
		argCnt = argCntStart[0]
	}
	for _, e := range wb.config {
		switch e.op {
		case OpIn:
			where.w += fmt.Sprintf(" AND (\"%s\"%s)", e.field, fmt.Sprintf(e.op.string(), fmt.Sprintf("$%d", argCnt)))
			argCnt++
			where.prms = append(where.prms, pq.Array(e.val))
			continue
		case OpIsNull:
			fallthrough
		case OpIsNotNull:
			where.w += fmt.Sprintf(" AND (\"%s\"%s)", e.field, e.op.string())
			continue
		default:
			where.w += fmt.Sprintf(" AND (\"%s\"%s)", e.field, fmt.Sprintf(e.op.string(), fmt.Sprintf("$%d", argCnt)))
			argCnt++
			where.prms = append(where.prms, e.val)
			continue
		}
	}
	return
}

type nothingWbログ struct{}

func (wb *nothingWbログ) And(field fldログ, op whereBuilderOperater, val interface{}) Wbログ {
	return wb
}
func (wb *nothingWbログ) Clear() {}
func (wb *nothingWbログ) build(argCntStart ...int) (where Where) {
	return Where{w: " AND 1<>1"}
}
func NewNothingWbログ() Wbログ {
	return &nothingWbログ{}
}
