// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import (
	"fmt"
	pq "github.com/lib/pq"
)

type Wbログ画面操作時 interface {
	And(field fldログ画面操作時, op whereBuilderOperater, val interface{}) Wbログ画面操作時
	Clear()
	build(argCntStart ...int) (where Where)
}
type wbログ画面操作時 struct {
	config []whereBuilderExp
}

func NewWbログ画面操作時() Wbログ画面操作時 {
	return &wbログ画面操作時{config: make([]whereBuilderExp, 0)}
}
func newWbログ画面操作時WithPrimaryKeys(No Id) Wbログ画面操作時 {
	wb := &wbログ画面操作時{config: make([]whereBuilderExp, 0)}
	wb.And(Tblログ画面操作時().FldNo(), OpEqu, No)

	return wb
}
func (wb *wbログ画面操作時) And(field fldログ画面操作時, op whereBuilderOperater, val interface{}) Wbログ画面操作時 {
	wb.config = append(wb.config, whereBuilderExp{
		field: string(field),
		op:    op,
		val:   val,
	})
	return wb
}
func (wb *wbログ画面操作時) Clear() {
	wb.config = make([]whereBuilderExp, 0)
}
func (wb *wbログ画面操作時) build(argCntStart ...int) (where Where) {
	where.w = ""
	where.prms = make([]interface{}, 0, len(wb.config))
	argCnt := 1
	if len(argCntStart) == 1 {
		argCnt = argCntStart[0]
	}
	for _, e := range wb.config {
		switch e.op {
		case OpIn:
			where.w += fmt.Sprintf(" AND (\"%s\"%s)", e.field, fmt.Sprintf(e.op.string(), fmt.Sprintf("$%d", argCnt)))
			argCnt++
			where.prms = append(where.prms, pq.Array(e.val))
			continue
		case OpIsNull:
			fallthrough
		case OpIsNotNull:
			where.w += fmt.Sprintf(" AND (\"%s\"%s)", e.field, e.op.string())
			continue
		default:
			where.w += fmt.Sprintf(" AND (\"%s\"%s)", e.field, fmt.Sprintf(e.op.string(), fmt.Sprintf("$%d", argCnt)))
			argCnt++
			where.prms = append(where.prms, e.val)
			continue
		}
	}
	return
}

type nothingWbログ画面操作時 struct{}

func (wb *nothingWbログ画面操作時) And(field fldログ画面操作時, op whereBuilderOperater, val interface{}) Wbログ画面操作時 {
	return wb
}
func (wb *nothingWbログ画面操作時) Clear() {}
func (wb *nothingWbログ画面操作時) build(argCntStart ...int) (where Where) {
	return Where{w: " AND 1<>1"}
}
func NewNothingWbログ画面操作時() Wbログ画面操作時 {
	return &nothingWbログ画面操作時{}
}
