// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import (
	objects "techbookfest16-sample/domain/objects"
	"time"
)

type Dtoログ struct {
	FldNo   Id
	Fld登録日時 time.Time
	Fld区分   objects.Enumログ区分
	Fld内容   string

	rowState DataRowState
	Ub       *ubログ `json:"-"`
}

func (d Dtoログ) TableName() string {
	return "ログ"
}
func (d Dtoログ) RowState() DataRowState {
	return d.rowState
}

// Import はDtoログ型に主キー以外を上書きする。
func (d *Dtoログ) Import(登録日時 time.Time, 区分 objects.Enumログ区分, 内容 string) {
	// 項目がすべて一致していたら、何もしない
	if d.Fld登録日時 == 登録日時 && d.Fld区分 == 区分 && d.Fld内容 == 内容 {
		return
	}
	if d.Fld登録日時 != 登録日時 {
		d.Fld登録日時 = 登録日時
		d.Ub.Set(Tblログ().Fld登録日時(), 登録日時)
	}
	if d.Fld区分 != 区分 {
		d.Fld区分 = 区分
		d.Ub.Set(Tblログ().Fld区分(), 区分)
	}
	if d.Fld内容 != 内容 {
		d.Fld内容 = 内容
		d.Ub.Set(Tblログ().Fld内容(), 内容)
	}

}
