// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

type tblログアップロード時 string

func Tblログアップロード時() tblログアップロード時 {
	return tblログアップロード時("ログ_アップロード時")
}

type fldログアップロード時 string

func (t tblログアップロード時) FldID() fldログアップロード時 {
	return fldログアップロード時("ID")
}
func (t tblログアップロード時) Fldアップロード履歴ID() fldログアップロード時 {
	return fldログアップロード時("アップロード履歴ID")
}
