// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import (
	"database/sql"
	"fmt"
	a "github.com/Moiterika/a"
	xerrors "golang.org/x/xerrors"
	"strconv"
	"strings"
	types "techbookfest16-sample/domain/types"
)

type daoTrnログ画面操作時 struct {
	dm        *DaoTrnManager
	trn       *sql.Tx
	WbForInit Wbログ画面操作時
}

func (d *daoTrnログ画面操作時) init() (err error) {
	d.dm.dtログ画面操作時, err = d.SelectW(d.WbForInit)
	if err != nil {
		return xerrors.Errorf(": %w", err)
	}
	d.dm.mapIDvsDrログ画面操作時 = a.ToMap(d.dm.dtログ画面操作時, func(e *Dtoログ画面操作時) Id {
		return e.FldNo
	})
	return
}
func (d *daoTrnログ画面操作時) Reset() {
	list := make([]*Dtoログ画面操作時, 0, len(d.dm.dtログ画面操作時))
	for _, dr := range d.dm.dtログ画面操作時 {
		if dr.rowState == Deleted {
			dr.rowState = Detached
			continue
		} else {
			dr.rowState = UnChanged
			list = append(list, dr)
		}
	}
	d.dm.dtログ画面操作時 = list
}
func (d daoTrnログ画面操作時) Dt() ([]*Dtoログ画面操作時, error) {
	if len(d.dm.dtログ画面操作時) == 0 {
		err := d.init()
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return nil, err
		}
	}
	return d.dm.dtログ画面操作時, nil
}
func (d daoTrnログ画面操作時) GetBy(id Id) (dr *Dtoログ画面操作時, err error) {
	if len(d.dm.mapIDvsDrログ画面操作時) == 0 {
		err = d.init()
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
	}
	var ok bool
	dr, ok = d.dm.mapIDvsDrログ画面操作時[id]
	if !ok {
		err = xerrors.Errorf("ログ_画面操作時が見つかりません。No=%d: %w", id, types.ErrNotFound)
		return
	}
	return
}
func (d daoTrnログ画面操作時) SelectAll() ([]*Dtoログ画面操作時, error) {
	sql := fmt.Sprintf(sqlSelectログ画面操作時, "")
	rows, err := d.trn.Query(sql)
	if err != nil {
		return nil, xerrors.Errorf("sql=%s: %w", sql, err)
	}
	defer rows.Close()
	var dt []*Dtoログ画面操作時
	for rows.Next() {
		var dr Dtoログ画面操作時
		err = rows.Scan(&dr.FldNo, &dr.Fld操作ユーザーID)
		if err != nil {
			return nil, xerrors.Errorf(": %w", err)
		}
		dr.rowState = Detached
		dr.Ub = NewUbログ画面操作時()
		dt = append(dt, &dr)
	}
	return dt, rows.Err()
}
func (d daoTrnログ画面操作時) SelectW(wb Wbログ画面操作時) ([]*Dtoログ画面操作時, error) {
	where := wb.build()
	prms, exists := where.Params()
	if exists {
		sql := fmt.Sprintf(sqlSelectログ画面操作時, where.String())
		rows, err := d.trn.Query(sql, prms...)
		if err != nil {
			return nil, xerrors.Errorf("sql=%s, args=%v: %w", sql, prms, err)
		}
		defer rows.Close()
		var dt []*Dtoログ画面操作時
		for rows.Next() {
			var dr Dtoログ画面操作時
			err = rows.Scan(&dr.FldNo, &dr.Fld操作ユーザーID)
			if err != nil {
				return nil, xerrors.Errorf(": %w", err)
			}
			dr.rowState = Detached
			dr.Ub = NewUbログ画面操作時()
			dt = append(dt, &dr)
		}
		return dt, rows.Err()
	} else {
		return d.SelectAll()
	}
}
func (d daoTrnログ画面操作時) Count() (cnt int64, err error) {
	return d.CountW(NewWbログ画面操作時())
}
func (d daoTrnログ画面操作時) CountW(wb Wbログ画面操作時) (cnt int64, err error) {
	where := wb.build()
	prms, exists := where.Params()
	if exists {
		err = d.trn.QueryRow(fmt.Sprintf(sqlSelectログ画面操作時ForAggregation, "count(\"No\")", where.String()), prms...).Scan(&cnt)
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
		return
	} else {
		err = d.trn.QueryRow(fmt.Sprintf(sqlSelectログ画面操作時ForAggregation, "count(\"No\")", "")).Scan(&cnt)
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
		return
	}
}

// Min はログ_画面操作時のfld最小値を返します。
func (d daoTrnログ画面操作時) Min(fld fldログ画面操作時) (min int64, err error) {
	return d.MinW(fld, NewWbログ画面操作時())
}
func (d daoTrnログ画面操作時) MinW(fld fldログ画面操作時, wb Wbログ画面操作時) (min int64, err error) {
	where := wb.build()
	prms, exists := where.Params()
	var x sql.NullInt64
	if exists {
		err = d.trn.QueryRow(fmt.Sprintf(sqlSelectログ画面操作時ForAggregation, fmt.Sprintf("min(%s)", strconv.Quote(string(fld))), where.String()), prms...).Scan(&x)
	} else {
		err = d.trn.QueryRow(fmt.Sprintf(sqlSelectログ画面操作時ForAggregation, fmt.Sprintf("min(%s)", strconv.Quote(string(fld))), where.String())).Scan(&x)
	}
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	if !x.Valid {
		err = xerrors.Errorf(": %w", types.ErrNotFound)
		return
	}
	min = x.Int64
	return
}

// Max はログ_画面操作時のfld最大値を返します。
func (d daoTrnログ画面操作時) Max(fld fldログ画面操作時) (max int64, err error) {
	return d.MaxW(fld, NewWbログ画面操作時())
}
func (d daoTrnログ画面操作時) MaxW(fld fldログ画面操作時, wb Wbログ画面操作時) (max int64, err error) {
	where := wb.build()
	prms, exists := where.Params()
	var x sql.NullInt64
	if exists {
		err = d.trn.QueryRow(fmt.Sprintf(sqlSelectログ画面操作時ForAggregation, fmt.Sprintf("max(%s)", strconv.Quote(string(fld))), where.String()), prms...).Scan(&x)
	} else {
		err = d.trn.QueryRow(fmt.Sprintf(sqlSelectログ画面操作時ForAggregation, fmt.Sprintf("max(%s)", strconv.Quote(string(fld))), where.String())).Scan(&x)
	}
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	if !x.Valid {
		err = xerrors.Errorf(": %w", types.ErrNotFound)
		return
	}
	max = x.Int64
	return
}
func (d daoTrnログ画面操作時) Insert(dr *Dtoログ画面操作時) (err error) {
	_, err = d.trn.Exec(sqlInsertログ画面操作時, dr.FldNo, dr.Fld操作ユーザーID)
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	dr.rowState = Added
	d.dm.dtログ画面操作時 = append(d.dm.dtログ画面操作時, dr)
	d.dm.mapIDvsDrログ画面操作時[dr.FldNo] = dr
	return
}
func (d daoTrnログ画面操作時) MultiInsert(dt []*Dtoログ画面操作時) (err error) {
	cs := a.Chunk(dt, 1000)
	for _, c := range cs {
		vals := make([]string, len(c))
		args := make([]interface{}, len(c)*2)
		for i, dr := range c {
			vals[i] = fmt.Sprintf(sqlValue2, 2*i+1, 2*i+2)
			args[2*i] = dr.FldNo
			args[2*i+1] = dr.Fld操作ユーザーID
			dr.rowState = Added
		}
		_, err = d.trn.Exec(fmt.Sprintf(sqlMultiInsertログ画面操作時, strings.Join(vals, ",")), args...)
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
	}
	return
}
func (d daoTrnログ画面操作時) UpdateBy(dr *Dtoログ画面操作時) (cnt int64, err error) {
	if dr.Ub.Count() == 0 {
		dr.rowState = UnChanged
		return
	}
	s, w, execArgs := dr.Ub.build(newWbログ画面操作時WithPrimaryKeys(dr.FldNo))
	sql := fmt.Sprintf(sqlUpdateログ画面操作時, s, w)
	result, err := d.trn.Exec(sql, execArgs...)
	if err != nil {
		err = xerrors.Errorf("sql=%s, args=%v: %w", sql, execArgs, err)
		return
	}
	cnt, err = result.RowsAffected()
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	dr.rowState = Modified
	return
}
func (d daoTrnログ画面操作時) UpdateW(ub *ubログ画面操作時, wb Wbログ画面操作時) (cnt int64, err error) {
	s, w, execArgs := ub.build(wb)
	sql := fmt.Sprintf(sqlUpdateログ画面操作時, s, w)
	result, err := d.trn.Exec(sql, execArgs...)
	if err != nil {
		err = xerrors.Errorf("sql=%s, args=%v: %w", sql, execArgs, err)
		return
	}
	cnt, err = result.RowsAffected()
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	return
}
func (d daoTrnログ画面操作時) DeleteBy(dr *Dtoログ画面操作時) (cnt int64, err error) {
	where := newWbログ画面操作時WithPrimaryKeys(dr.FldNo).build()
	prms, exists := where.Params()
	if !exists {
		err = xerrors.Errorf("主キーがありません。: %#v", *dr)
		return
	}
	sql := fmt.Sprintf(sqlDeleteログ画面操作時, where.String())
	result, errExec := d.trn.Exec(sql, prms...)
	if errExec != nil {
		err = xerrors.Errorf("sql=%s, args=%v: %w", sql, prms, errExec)
		return
	}
	cnt, err = result.RowsAffected()
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	dr.rowState = Deleted
	return
}
func (d daoTrnログ画面操作時) DeleteW(wb Wbログ画面操作時) (cnt int64, err error) {
	where := wb.build()
	prms, exists := where.Params()
	if exists {
		sql := fmt.Sprintf(sqlDeleteログ画面操作時, where.String())
		result, errExec := d.trn.Exec(sql, prms...)
		if errExec != nil {
			err = xerrors.Errorf("sql=%s, args=%v: %w", sql, prms, errExec)
			return
		}
		cnt, err = result.RowsAffected()
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
	} else {
		result, errExec := d.trn.Exec(sqlTruncateログ画面操作時)
		if errExec != nil {
			err = xerrors.Errorf("sql=%s: %w", sqlTruncateログ画面操作時, errExec)
			return
		}
		cnt, err = result.RowsAffected()
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
	}
	return
}
