// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import "fmt"

type ebログjoinログアップロード時 struct {
	wb Wbログアップロード時
}

func NewEbログjoinログアップロード時() *ebログjoinログアップロード時 {
	return &ebログjoinログアップロード時{wb: NewWbログアップロード時()}
}
func (eb *ebログjoinログアップロード時) And(field fldログアップロード時, op whereBuilderOperater, val interface{}) Ebログ {
	eb.wb.And(field, op, val)
	return eb
}
func (eb *ebログjoinログアップロード時) buildEbログ(argCntStart ...int) (where Where) {
	where = eb.wb.build(argCntStart...)
	where.w = fmt.Sprintf(" AND EXISTS (SELECT * FROM \"ログ_アップロード時\" WHERE \"ログ_アップロード時\".\"No\" = \"ログ\".\"No\" %s)", where.w)
	return
}
