// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import "fmt"

type ebログjoinログ画面操作時 struct {
	wb Wbログ画面操作時
}

func NewEbログjoinログ画面操作時() *ebログjoinログ画面操作時 {
	return &ebログjoinログ画面操作時{wb: NewWbログ画面操作時()}
}
func (eb *ebログjoinログ画面操作時) And(field fldログ画面操作時, op whereBuilderOperater, val interface{}) Ebログ {
	eb.wb.And(field, op, val)
	return eb
}
func (eb *ebログjoinログ画面操作時) buildEbログ(argCntStart ...int) (where Where) {
	where = eb.wb.build(argCntStart...)
	where.w = fmt.Sprintf(" AND EXISTS (SELECT * FROM \"ログ_画面操作時\" WHERE \"ログ_画面操作時\".\"No\" = \"ログ\".\"No\" %s)", where.w)
	return
}
