// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

type Dtoログアップロード時 struct {
	FldNo         Id
	Fldアップロード履歴ID Id

	rowState DataRowState
	Ub       *ubログアップロード時 `json:"-"`
}

func (d Dtoログアップロード時) TableName() string {
	return "ログ_アップロード時"
}
func (d Dtoログアップロード時) RowState() DataRowState {
	return d.rowState
}

// Import はDtoログアップロード時型に主キー以外を上書きする。
func (d *Dtoログアップロード時) Import(アップロード履歴ID Id) {
	// 項目がすべて一致していたら、何もしない
	if d.Fldアップロード履歴ID == アップロード履歴ID {
		return
	}
	if d.Fldアップロード履歴ID != アップロード履歴ID {
		d.Fldアップロード履歴ID = アップロード履歴ID
		d.Ub.Set(Tblログアップロード時().Fldアップロード履歴ID(), アップロード履歴ID)
	}

}
