// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import "fmt"

type ebログ画面操作時joinログ struct {
	wb Wbログ
}

func NewEbログ画面操作時joinログ() *ebログ画面操作時joinログ {
	return &ebログ画面操作時joinログ{wb: NewWbログ()}
}
func (eb *ebログ画面操作時joinログ) And(field fldログ, op whereBuilderOperater, val interface{}) Ebログ画面操作時 {
	eb.wb.And(field, op, val)
	return eb
}
func (eb *ebログ画面操作時joinログ) buildEbログ画面操作時(argCntStart ...int) (where Where) {
	where = eb.wb.build(argCntStart...)
	where.w = fmt.Sprintf(" AND EXISTS (SELECT * FROM \"ログ\" WHERE \"ログ\".\"No\" = \"ログ_画面操作時\".\"No\" %s)", where.w)
	return
}
