// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import (
	"fmt"
	pq "github.com/lib/pq"
)

type Wbログ interface {
	And(field fldログ, op whereBuilderOperater, val interface{}) Wbログ
	Clear()
	Exists(Ebログ) Wbログ
	build(argCntStart ...int) (where Where)
}
type wbログ struct {
	config []whereBuilderExp
	ebs    []Ebログ
}

func NewWbログ() Wbログ {
	return &wbログ{
		config: make([]whereBuilderExp, 0),
		ebs:    make([]Ebログ, 0),
	}
}
func newWbログWithPrimaryKeys(No Id) Wbログ {
	wb := &wbログ{config: make([]whereBuilderExp, 0)}
	wb.And(Tblログ().FldNo(), OpEqu, No)

	return wb
}
func (wb *wbログ) And(field fldログ, op whereBuilderOperater, val interface{}) Wbログ {
	wb.config = append(wb.config, whereBuilderExp{
		field: string(field),
		op:    op,
		val:   val,
	})
	return wb
}
func (wb *wbログ) Clear() {
	wb.config = make([]whereBuilderExp, 0)
}
func (wb *wbログ) Exists(eb Ebログ) Wbログ {
	wb.ebs = append(wb.ebs, eb)
	return wb
}
func (wb *wbログ) build(argsCntStart ...int) (where Where) {
	where.w = ""
	where.prms = make([]interface{}, 0, len(wb.config))
	if len(argsCntStart) == 1 {
		where.argsCnt = argsCntStart[0]
	}
	for _, e := range wb.config {
		switch e.op {
		case OpIn:
			where.argsCnt++
			where.w += fmt.Sprintf(" AND (\"%s\"%s)", e.field, fmt.Sprintf(e.op.string(), fmt.Sprintf("$%d", where.argsCnt)))
			where.prms = append(where.prms, pq.Array(e.val))
			continue
		case OpIsNull:
			fallthrough
		case OpIsNotNull:
			where.w += fmt.Sprintf(" AND (\"%s\"%s)", e.field, e.op.string())
			continue
		default:
			where.argsCnt++
			where.w += fmt.Sprintf(" AND (\"%s\"%s)", e.field, fmt.Sprintf(e.op.string(), fmt.Sprintf("$%d", where.argsCnt)))
			where.prms = append(where.prms, e.val)
			continue
		}
	}
	for _, eb := range wb.ebs {
		w := eb.buildEbログ(where.argsCnt)
		where.Append(w)
	}
	return
}

type nothingWbログ struct{}

func (wb *nothingWbログ) And(field fldログ, op whereBuilderOperater, val interface{}) Wbログ {
	return wb
}
func (wb *nothingWbログ) Clear() {}
func (wb *nothingWbログ) Exists(_ Ebログ) Wbログ {
	return wb
}
func (wb *nothingWbログ) build(argCntStart ...int) (where Where) {
	return Where{w: " AND 1<>1"}
}
func NewNothingWbログ() Wbログ {
	return &nothingWbログ{}
}
