// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

type tblログ string

func Tblログ() tblログ {
	return tblログ("ログ")
}

type fldログ string

func (t tblログ) FldNo() fldログ {
	return fldログ("No")
}
func (t tblログ) Fld登録日時() fldログ {
	return fldログ("登録日時")
}
func (t tblログ) Fld区分() fldログ {
	return fldログ("区分")
}
func (t tblログ) Fld内容() fldログ {
	return fldログ("内容")
}
