// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

type Dtoログ画面操作時 struct {
	FldNo       Id
	Fld操作ユーザーID Id

	rowState DataRowState
	Ub       *ubログ画面操作時 `json:"-"`
}

func (d Dtoログ画面操作時) TableName() string {
	return "ログ_画面操作時"
}
func (d Dtoログ画面操作時) RowState() DataRowState {
	return d.rowState
}

// Import はDtoログ画面操作時型に主キー以外を上書きする。
func (d *Dtoログ画面操作時) Import(操作ユーザーID Id) {
	// 項目がすべて一致していたら、何もしない
	if d.Fld操作ユーザーID == 操作ユーザーID {
		return
	}
	if d.Fld操作ユーザーID != 操作ユーザーID {
		d.Fld操作ユーザーID = 操作ユーザーID
		d.Ub.Set(Tblログ画面操作時().Fld操作ユーザーID(), 操作ユーザーID)
	}

}
