// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import "fmt"

type eb単位join受払仕入 struct {
	wb Wb受払仕入
}

func NewEb単位join受払仕入() *eb単位join受払仕入 {
	return &eb単位join受払仕入{wb: NewWb受払仕入()}
}
func (eb *eb単位join受払仕入) And(field fld受払仕入, op whereBuilderOperater, val interface{}) Eb単位 {
	eb.wb.And(field, op, val)
	return eb
}
func (eb *eb単位join受払仕入) buildEb単位(argCntStart ...int) (where Where) {
	where = eb.wb.build(argCntStart...)
	where.w = fmt.Sprintf(" AND EXISTS (SELECT * FROM \"受払_仕入\" WHERE \"受払_仕入\".\"仕入単位ID\" = \"単位\".\"ID\" %s)", where.w)
	return
}
