// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

type tbl単位 string

func Tbl単位() tbl単位 {
	return tbl単位("単位")
}

type fld単位 string

func (t tbl単位) FldID() fld単位 {
	return fld単位("ID")
}
func (t tbl単位) Fldコード() fld単位 {
	return fld単位("コード")
}
func (t tbl単位) Fld名称() fld単位 {
	return fld単位("名称")
}
