// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import "fmt"

type eb単位join受払 struct {
	wb Wb受払
}

func NewEb単位join受払() *eb単位join受払 {
	return &eb単位join受払{wb: NewWb受払()}
}
func (eb *eb単位join受払) And(field fld受払, op whereBuilderOperater, val interface{}) Eb単位 {
	eb.wb.And(field, op, val)
	return eb
}
func (eb *eb単位join受払) buildEb単位(argCntStart ...int) (where Where) {
	where = eb.wb.build(argCntStart...)
	where.w = fmt.Sprintf(" AND EXISTS (SELECT * FROM \"受払\" WHERE \"受払\".\"基準単位ID\" = \"単位\".\"ID\" %s)", where.w)
	return
}
