// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import "fmt"

type eb単位join受払製造実績 struct {
	wb Wb受払製造実績
}

func NewEb単位join受払製造実績() *eb単位join受払製造実績 {
	return &eb単位join受払製造実績{wb: NewWb受払製造実績()}
}
func (eb *eb単位join受払製造実績) And(field fld受払製造実績, op whereBuilderOperater, val interface{}) Eb単位 {
	eb.wb.And(field, op, val)
	return eb
}
func (eb *eb単位join受払製造実績) buildEb単位(argCntStart ...int) (where Where) {
	where = eb.wb.build(argCntStart...)
	where.w = fmt.Sprintf(" AND EXISTS (SELECT * FROM \"受払_製造実績\" WHERE \"受払_製造実績\".\"製造単位ID\" = \"単位\".\"ID\" %s)", where.w)
	return
}
