// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import (
	"fmt"
	pq "github.com/lib/pq"
	types "techbookfest16-sample/domain/types"
)

type Wb単位 interface {
	And(field fld単位, op whereBuilderOperater, val interface{}) Wb単位
	Clear()
	build(argCntStart ...int) (where Where)
}
type wb単位 struct {
	config []whereBuilderExp
}

func NewWb単位() Wb単位 {
	return &wb単位{config: make([]whereBuilderExp, 0)}
}
func newWb単位WithPrimaryKeys(ID types.Unit) Wb単位 {
	wb := &wb単位{config: make([]whereBuilderExp, 0)}
	wb.And(Tbl単位().FldID(), OpEqu, ID)

	return wb
}
func (wb *wb単位) And(field fld単位, op whereBuilderOperater, val interface{}) Wb単位 {
	wb.config = append(wb.config, whereBuilderExp{
		field: string(field),
		op:    op,
		val:   val,
	})
	return wb
}
func (wb *wb単位) Clear() {
	wb.config = make([]whereBuilderExp, 0)
}
func (wb *wb単位) build(argCntStart ...int) (where Where) {
	where.w = ""
	where.prms = make([]interface{}, 0, len(wb.config))
	argCnt := 1
	if len(argCntStart) == 1 {
		argCnt = argCntStart[0]
	}
	for _, e := range wb.config {
		switch e.op {
		case OpIn:
			where.w += fmt.Sprintf(" AND (\"%s\"%s)", e.field, fmt.Sprintf(e.op.string(), fmt.Sprintf("$%d", argCnt)))
			argCnt++
			where.prms = append(where.prms, pq.Array(e.val))
			continue
		case OpIsNull:
			fallthrough
		case OpIsNotNull:
			where.w += fmt.Sprintf(" AND (\"%s\"%s)", e.field, e.op.string())
			continue
		default:
			where.w += fmt.Sprintf(" AND (\"%s\"%s)", e.field, fmt.Sprintf(e.op.string(), fmt.Sprintf("$%d", argCnt)))
			argCnt++
			where.prms = append(where.prms, e.val)
			continue
		}
	}
	return
}

type nothingWb単位 struct{}

func (wb *nothingWb単位) And(field fld単位, op whereBuilderOperater, val interface{}) Wb単位 {
	return wb
}
func (wb *nothingWb単位) Clear() {}
func (wb *nothingWb単位) build(argCntStart ...int) (where Where) {
	return Where{w: " AND 1<>1"}
}
func NewNothingWb単位() Wb単位 {
	return &nothingWb単位{}
}
