// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import "fmt"

type eb単位join品目仕入品 struct {
	wb Wb品目仕入品
}

func NewEb単位join品目仕入品() *eb単位join品目仕入品 {
	return &eb単位join品目仕入品{wb: NewWb品目仕入品()}
}
func (eb *eb単位join品目仕入品) And(field fld品目仕入品, op whereBuilderOperater, val interface{}) Eb単位 {
	eb.wb.And(field, op, val)
	return eb
}
func (eb *eb単位join品目仕入品) buildEb単位(argCntStart ...int) (where Where) {
	where = eb.wb.build(argCntStart...)
	where.w = fmt.Sprintf(" AND EXISTS (SELECT * FROM \"品目_仕入品\" WHERE \"品目_仕入品\".\"標準単価単位ID\" = \"単位\".\"ID\" %s)", where.w)
	return
}
