// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import "fmt"

type eb単位join品目 struct {
	wb Wb品目
}

func NewEb単位join品目() *eb単位join品目 {
	return &eb単位join品目{wb: NewWb品目()}
}
func (eb *eb単位join品目) And(field fld品目, op whereBuilderOperater, val interface{}) Eb単位 {
	eb.wb.And(field, op, val)
	return eb
}
func (eb *eb単位join品目) buildEb単位(argCntStart ...int) (where Where) {
	where = eb.wb.build(argCntStart...)
	where.w = fmt.Sprintf(" AND EXISTS (SELECT * FROM \"品目\" WHERE \"品目\".\"基準単位ID\" = \"単位\".\"ID\" %s)", where.w)
	return
}
