// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import "fmt"

type eb単位join受払出荷 struct {
	wb Wb受払出荷
}

func NewEb単位join受払出荷() *eb単位join受払出荷 {
	return &eb単位join受払出荷{wb: NewWb受払出荷()}
}
func (eb *eb単位join受払出荷) And(field fld受払出荷, op whereBuilderOperater, val interface{}) Eb単位 {
	eb.wb.And(field, op, val)
	return eb
}
func (eb *eb単位join受払出荷) buildEb単位(argCntStart ...int) (where Where) {
	where = eb.wb.build(argCntStart...)
	where.w = fmt.Sprintf(" AND EXISTS (SELECT * FROM \"受払_出荷\" WHERE \"受払_出荷\".\"出荷単位ID\" = \"単位\".\"ID\" %s)", where.w)
	return
}
