// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import "fmt"

type eb受払join受払投入実績 struct {
	wb Wb受払投入実績
}

func NewEb受払join受払投入実績() *eb受払join受払投入実績 {
	return &eb受払join受払投入実績{wb: NewWb受払投入実績()}
}
func (eb *eb受払join受払投入実績) And(field fld受払投入実績, op whereBuilderOperater, val interface{}) Eb受払 {
	eb.wb.And(field, op, val)
	return eb
}
func (eb *eb受払join受払投入実績) buildEb受払(argCntStart ...int) (where Where) {
	where = eb.wb.build(argCntStart...)
	where.w = fmt.Sprintf(" AND EXISTS (SELECT * FROM \"受払_投入実績\" WHERE \"受払_投入実績\".\"No\" = \"受払\".\"No\" %s)", where.w)
	return
}
