// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

type tbl受払出荷 string

func Tbl受払出荷() tbl受払出荷 {
	return tbl受払出荷("受払_出荷")
}

type fld受払出荷 string

func (t tbl受払出荷) FldNo() fld受払出荷 {
	return fld受払出荷("No")
}
func (t tbl受払出荷) Fld出荷数量() fld受払出荷 {
	return fld受払出荷("出荷数量")
}
func (t tbl受払出荷) Fld出荷単位ID() fld受払出荷 {
	return fld受払出荷("出荷単位ID")
}
