// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import (
	decimal "github.com/shopspring/decimal"
	types "techbookfest16-sample/domain/types"
)

type Dto受払投入実績 struct {
	FldNo     Id
	Fld投入数量   decimal.Decimal
	Fld投入単位ID types.Unit
	Fld製造指図ID Id

	rowState DataRowState
	Ub       *ub受払投入実績 `json:"-"`
}

func (d Dto受払投入実績) TableName() string {
	return "受払_投入実績"
}
func (d Dto受払投入実績) RowState() DataRowState {
	return d.rowState
}

// Import はDto受払投入実績型に主キー以外を上書きする。
func (d *Dto受払投入実績) Import(投入数量 decimal.Decimal, 投入単位ID types.Unit, 製造指図ID Id) {
	// 項目がすべて一致していたら、何もしない
	if d.Fld投入数量 == 投入数量 && d.Fld投入単位ID == 投入単位ID && d.Fld製造指図ID == 製造指図ID {
		return
	}
	if d.Fld投入数量 != 投入数量 {
		d.Fld投入数量 = 投入数量
		d.Ub.Set(Tbl受払投入実績().Fld投入数量(), 投入数量)
	}
	if d.Fld投入単位ID != 投入単位ID {
		d.Fld投入単位ID = 投入単位ID
		d.Ub.Set(Tbl受払投入実績().Fld投入単位ID(), 投入単位ID)
	}
	if d.Fld製造指図ID != 製造指図ID {
		d.Fld製造指図ID = 製造指図ID
		d.Ub.Set(Tbl受払投入実績().Fld製造指図ID(), 製造指図ID)
	}

}
