// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import (
	"fmt"
	pq "github.com/lib/pq"
)

type Wb受払仕入 interface {
	And(field fld受払仕入, op whereBuilderOperater, val interface{}) Wb受払仕入
	Clear()
	Exists(Eb受払仕入) Wb受払仕入
	build(argCntStart ...int) (where Where)
}
type wb受払仕入 struct {
	config []whereBuilderExp
	ebs    []Eb受払仕入
}

func NewWb受払仕入() Wb受払仕入 {
	return &wb受払仕入{
		config: make([]whereBuilderExp, 0),
		ebs:    make([]Eb受払仕入, 0),
	}
}
func newWb受払仕入WithPrimaryKeys(No Id) Wb受払仕入 {
	wb := &wb受払仕入{config: make([]whereBuilderExp, 0)}
	wb.And(Tbl受払仕入().FldNo(), OpEqu, No)

	return wb
}
func (wb *wb受払仕入) And(field fld受払仕入, op whereBuilderOperater, val interface{}) Wb受払仕入 {
	wb.config = append(wb.config, whereBuilderExp{
		field: string(field),
		op:    op,
		val:   val,
	})
	return wb
}
func (wb *wb受払仕入) Clear() {
	wb.config = make([]whereBuilderExp, 0)
}
func (wb *wb受払仕入) Exists(eb Eb受払仕入) Wb受払仕入 {
	wb.ebs = append(wb.ebs, eb)
	return wb
}
func (wb *wb受払仕入) build(argsCntStart ...int) (where Where) {
	where.w = ""
	where.prms = make([]interface{}, 0, len(wb.config))
	if len(argsCntStart) == 1 {
		where.argsCnt = argsCntStart[0]
	}
	for _, e := range wb.config {
		switch e.op {
		case OpIn:
			where.argsCnt++
			where.w += fmt.Sprintf(" AND (\"%s\"%s)", e.field, fmt.Sprintf(e.op.string(), fmt.Sprintf("$%d", where.argsCnt)))
			where.prms = append(where.prms, pq.Array(e.val))
			continue
		case OpIsNull:
			fallthrough
		case OpIsNotNull:
			where.w += fmt.Sprintf(" AND (\"%s\"%s)", e.field, e.op.string())
			continue
		default:
			where.argsCnt++
			where.w += fmt.Sprintf(" AND (\"%s\"%s)", e.field, fmt.Sprintf(e.op.string(), fmt.Sprintf("$%d", where.argsCnt)))
			where.prms = append(where.prms, e.val)
			continue
		}
	}
	for _, eb := range wb.ebs {
		w := eb.buildEb受払仕入(where.argsCnt)
		where.Append(w)
	}
	return
}

type nothingWb受払仕入 struct{}

func (wb *nothingWb受払仕入) And(field fld受払仕入, op whereBuilderOperater, val interface{}) Wb受払仕入 {
	return wb
}
func (wb *nothingWb受払仕入) Clear() {}
func (wb *nothingWb受払仕入) Exists(_ Eb受払仕入) Wb受払仕入 {
	return wb
}
func (wb *nothingWb受払仕入) build(argCntStart ...int) (where Where) {
	return Where{w: " AND 1<>1"}
}
func NewNothingWb受払仕入() Wb受払仕入 {
	return &nothingWb受払仕入{}
}
