// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import "fmt"

type eb受払join品目 struct {
	wb Wb品目
}

func NewEb受払join品目() *eb受払join品目 {
	return &eb受払join品目{wb: NewWb品目()}
}
func (eb *eb受払join品目) And(field fld品目, op whereBuilderOperater, val interface{}) Eb受払 {
	eb.wb.And(field, op, val)
	return eb
}
func (eb *eb受払join品目) buildEb受払(argCntStart ...int) (where Where) {
	where = eb.wb.build(argCntStart...)
	where.w = fmt.Sprintf(" AND EXISTS (SELECT * FROM \"品目\" WHERE \"品目\".\"ID\" = \"受払\".\"品目ID\" %s)", where.w)
	return
}
