// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

type tbl受払仕入 string

func Tbl受払仕入() tbl受払仕入 {
	return tbl受払仕入("受払_仕入")
}

type fld受払仕入 string

func (t tbl受払仕入) FldNo() fld受払仕入 {
	return fld受払仕入("No")
}
func (t tbl受払仕入) Fld仕入数量() fld受払仕入 {
	return fld受払仕入("仕入数量")
}
func (t tbl受払仕入) Fld仕入単位ID() fld受払仕入 {
	return fld受払仕入("仕入単位ID")
}
func (t tbl受払仕入) Fld仕入金額() fld受払仕入 {
	return fld受払仕入("仕入金額")
}
func (t tbl受払仕入) Fld仕入通貨ID() fld受払仕入 {
	return fld受払仕入("仕入通貨ID")
}
func (t tbl受払仕入) Fld仕入単価() fld受払仕入 {
	return fld受払仕入("仕入単価")
}
