// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import decimal "github.com/shopspring/decimal"

type Dto受払出荷 struct {
	FldNo     Id
	Fld出荷数量   decimal.Decimal
	Fld出荷単位ID Id

	rowState DataRowState
	Ub       *ub受払出荷 `json:"-"`
}

func (d Dto受払出荷) TableName() string {
	return "受払_出荷"
}
func (d Dto受払出荷) RowState() DataRowState {
	return d.rowState
}

// Import はDto受払出荷型に主キー以外を上書きする。
func (d *Dto受払出荷) Import(出荷数量 decimal.Decimal, 出荷単位ID Id) {
	// 項目がすべて一致していたら、何もしない
	if d.Fld出荷数量 == 出荷数量 && d.Fld出荷単位ID == 出荷単位ID {
		return
	}
	if d.Fld出荷数量 != 出荷数量 {
		d.Fld出荷数量 = 出荷数量
		d.Ub.Set(Tbl受払出荷().Fld出荷数量(), 出荷数量)
	}
	if d.Fld出荷単位ID != 出荷単位ID {
		d.Fld出荷単位ID = 出荷単位ID
		d.Ub.Set(Tbl受払出荷().Fld出荷単位ID(), 出荷単位ID)
	}

}
