// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

type tbl受払製造実績 string

func Tbl受払製造実績() tbl受払製造実績 {
	return tbl受払製造実績("受払_製造実績")
}

type fld受払製造実績 string

func (t tbl受払製造実績) FldNo() fld受払製造実績 {
	return fld受払製造実績("No")
}
func (t tbl受払製造実績) Fld製造数量() fld受払製造実績 {
	return fld受払製造実績("製造数量")
}
func (t tbl受払製造実績) Fld製造単位ID() fld受払製造実績 {
	return fld受払製造実績("製造単位ID")
}
func (t tbl受払製造実績) Fld製造指図ID() fld受払製造実績 {
	return fld受払製造実績("製造指図ID")
}
