// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

type tbl受払投入実績 string

func Tbl受払投入実績() tbl受払投入実績 {
	return tbl受払投入実績("受払_投入実績")
}

type fld受払投入実績 string

func (t tbl受払投入実績) FldNo() fld受払投入実績 {
	return fld受払投入実績("No")
}
func (t tbl受払投入実績) Fld投入数量() fld受払投入実績 {
	return fld受払投入実績("投入数量")
}
func (t tbl受払投入実績) Fld投入単位ID() fld受払投入実績 {
	return fld受払投入実績("投入単位ID")
}
func (t tbl受払投入実績) Fld製造指図ID() fld受払投入実績 {
	return fld受払投入実績("製造指図ID")
}
