// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import (
	"database/sql"
	"fmt"
	a "github.com/Moiterika/a"
	xerrors "golang.org/x/xerrors"
	"strconv"
	"strings"
	types "techbookfest16-sample/domain/types"
)

type daoDb受払仕入 struct {
	dm        *DaoDbManager
	db        *sql.DB
	WbForInit Wb受払仕入
}

func (d *daoDb受払仕入) init() (err error) {
	d.dm.dt受払仕入, err = d.SelectW(d.WbForInit)
	if err != nil {
		return xerrors.Errorf(": %w", err)
	}
	d.dm.mapIDvsDr受払仕入 = a.ToMap(d.dm.dt受払仕入, func(e *Dto受払仕入) Id {
		return e.FldNo
	})
	return
}
func (d *daoDb受払仕入) Reset() {
	list := make([]*Dto受払仕入, 0, len(d.dm.dt受払仕入))
	for _, dr := range d.dm.dt受払仕入 {
		if dr.rowState == Deleted {
			dr.rowState = Detached
			continue
		} else {
			dr.rowState = UnChanged
			list = append(list, dr)
		}
	}
	d.dm.dt受払仕入 = list
}
func (d daoDb受払仕入) Dt() ([]*Dto受払仕入, error) {
	if len(d.dm.dt受払仕入) == 0 {
		err := d.init()
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return nil, err
		}
	}
	return d.dm.dt受払仕入, nil
}
func (d daoDb受払仕入) GetBy(id Id) (dr *Dto受払仕入, err error) {
	if len(d.dm.mapIDvsDr受払仕入) == 0 {
		err = d.init()
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
	}
	var ok bool
	dr, ok = d.dm.mapIDvsDr受払仕入[id]
	if !ok {
		err = xerrors.Errorf("受払_仕入が見つかりません。No=%d: %w", id, types.ErrNotFound)
		return
	}
	return
}
func (d daoDb受払仕入) SelectAll() ([]*Dto受払仕入, error) {
	sql := fmt.Sprintf(sqlSelect受払仕入, "")
	rows, err := d.db.Query(sql)
	if err != nil {
		return nil, xerrors.Errorf("sql=%s: %w", sql, err)
	}
	defer rows.Close()
	var dt []*Dto受払仕入
	for rows.Next() {
		var dr Dto受払仕入
		err = rows.Scan(&dr.FldNo, &dr.Fld仕入数量, &dr.Fld仕入単位ID, &dr.Fld仕入金額, &dr.Fld仕入通貨ID, &dr.Fld仕入単価)
		if err != nil {
			return nil, xerrors.Errorf(": %w", err)
		}
		dr.rowState = Detached
		dr.Ub = NewUb受払仕入()
		dt = append(dt, &dr)
	}
	return dt, rows.Err()
}
func (d daoDb受払仕入) SelectW(wb Wb受払仕入) ([]*Dto受払仕入, error) {
	where := wb.build()
	prms, exists := where.Params()
	if exists {
		sql := fmt.Sprintf(sqlSelect受払仕入, where.String())
		rows, err := d.db.Query(sql, prms...)
		if err != nil {
			return nil, xerrors.Errorf("sql=%s, args=%v: %w", sql, prms, err)
		}
		defer rows.Close()
		var dt []*Dto受払仕入
		for rows.Next() {
			var dr Dto受払仕入
			err = rows.Scan(&dr.FldNo, &dr.Fld仕入数量, &dr.Fld仕入単位ID, &dr.Fld仕入金額, &dr.Fld仕入通貨ID, &dr.Fld仕入単価)
			if err != nil {
				return nil, xerrors.Errorf(": %w", err)
			}
			dr.rowState = Detached
			dr.Ub = NewUb受払仕入()
			dt = append(dt, &dr)
		}
		return dt, rows.Err()
	} else {
		return d.SelectAll()
	}
}
func (d daoDb受払仕入) Count() (cnt int64, err error) {
	return d.CountW(NewWb受払仕入())
}
func (d daoDb受払仕入) CountW(wb Wb受払仕入) (cnt int64, err error) {
	where := wb.build()
	prms, exists := where.Params()
	if exists {
		err = d.db.QueryRow(fmt.Sprintf(sqlSelect受払仕入ForAggregation, "count(\"No\")", where.String()), prms...).Scan(&cnt)
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
		return
	} else {
		err = d.db.QueryRow(fmt.Sprintf(sqlSelect受払仕入ForAggregation, "count(\"No\")", "")).Scan(&cnt)
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
		return
	}
}

// Min は受払_仕入のfld最小値を返します。
func (d daoDb受払仕入) Min(fld fld受払仕入) (min int64, err error) {
	return d.MinW(fld, NewWb受払仕入())
}
func (d daoDb受払仕入) MinW(fld fld受払仕入, wb Wb受払仕入) (min int64, err error) {
	where := wb.build()
	prms, exists := where.Params()
	var x sql.NullInt64
	if exists {
		err = d.db.QueryRow(fmt.Sprintf(sqlSelect受払仕入ForAggregation, fmt.Sprintf("min(%s)", strconv.Quote(string(fld))), where.String()), prms...).Scan(&x)
	} else {
		err = d.db.QueryRow(fmt.Sprintf(sqlSelect受払仕入ForAggregation, fmt.Sprintf("min(%s)", strconv.Quote(string(fld))), where.String())).Scan(&x)
	}
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	if !x.Valid {
		err = xerrors.Errorf(": %w", types.ErrNotFound)
		return
	}
	min = x.Int64
	return
}

// Max は受払_仕入のfld最大値を返します。
func (d daoDb受払仕入) Max(fld fld受払仕入) (max int64, err error) {
	return d.MaxW(fld, NewWb受払仕入())
}
func (d daoDb受払仕入) MaxW(fld fld受払仕入, wb Wb受払仕入) (max int64, err error) {
	where := wb.build()
	prms, exists := where.Params()
	var x sql.NullInt64
	if exists {
		err = d.db.QueryRow(fmt.Sprintf(sqlSelect受払仕入ForAggregation, fmt.Sprintf("max(%s)", strconv.Quote(string(fld))), where.String()), prms...).Scan(&x)
	} else {
		err = d.db.QueryRow(fmt.Sprintf(sqlSelect受払仕入ForAggregation, fmt.Sprintf("max(%s)", strconv.Quote(string(fld))), where.String())).Scan(&x)
	}
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	if !x.Valid {
		err = xerrors.Errorf(": %w", types.ErrNotFound)
		return
	}
	max = x.Int64
	return
}
func (d daoDb受払仕入) Insert(dr *Dto受払仕入) (err error) {
	_, err = d.db.Exec(sqlInsert受払仕入, dr.FldNo, dr.Fld仕入数量, dr.Fld仕入単位ID, dr.Fld仕入金額, dr.Fld仕入通貨ID, dr.Fld仕入単価)
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	dr.rowState = Added
	d.dm.dt受払仕入 = append(d.dm.dt受払仕入, dr)
	d.dm.mapIDvsDr受払仕入[dr.FldNo] = dr
	return
}
func (d daoDb受払仕入) MultiInsert(dt []*Dto受払仕入) (err error) {
	cs := a.Chunk(dt, 1000)
	for _, c := range cs {
		vals := make([]string, len(c))
		args := make([]interface{}, len(c)*6)
		for i, dr := range c {
			vals[i] = fmt.Sprintf(sqlValue6, 6*i+1, 6*i+2, 6*i+3, 6*i+4, 6*i+5, 6*i+6)
			args[6*i] = dr.FldNo
			args[6*i+1] = dr.Fld仕入数量
			args[6*i+2] = dr.Fld仕入単位ID
			args[6*i+3] = dr.Fld仕入金額
			args[6*i+4] = dr.Fld仕入通貨ID
			args[6*i+5] = dr.Fld仕入単価
			dr.rowState = Added
		}
		_, err = d.db.Exec(fmt.Sprintf(sqlMultiInsert受払仕入, strings.Join(vals, ",")), args...)
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
	}
	return
}
func (d daoDb受払仕入) UpdateBy(dr *Dto受払仕入) (cnt int64, err error) {
	if dr.Ub.Count() == 0 {
		dr.rowState = UnChanged
		return
	}
	s, w, execArgs := dr.Ub.build(newWb受払仕入WithPrimaryKeys(dr.FldNo))
	sql := fmt.Sprintf(sqlUpdate受払仕入, s, w)
	result, err := d.db.Exec(sql, execArgs...)
	if err != nil {
		err = xerrors.Errorf("sql=%s, args=%v: %w", sql, execArgs, err)
		return
	}
	cnt, err = result.RowsAffected()
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	dr.rowState = Modified
	return
}
func (d daoDb受払仕入) UpdateW(ub *ub受払仕入, wb Wb受払仕入) (cnt int64, err error) {
	s, w, execArgs := ub.build(wb)
	sql := fmt.Sprintf(sqlUpdate受払仕入, s, w)
	result, err := d.db.Exec(sql, execArgs...)
	if err != nil {
		err = xerrors.Errorf("sql=%s, args=%v: %w", sql, execArgs, err)
		return
	}
	cnt, err = result.RowsAffected()
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	return
}
func (d daoDb受払仕入) DeleteBy(dr *Dto受払仕入) (cnt int64, err error) {
	where := newWb受払仕入WithPrimaryKeys(dr.FldNo).build()
	prms, exists := where.Params()
	if !exists {
		err = xerrors.Errorf("主キーがありません。: %#v", *dr)
		return
	}
	sql := fmt.Sprintf(sqlDelete受払仕入, where.String())
	result, errExec := d.db.Exec(sql, prms...)
	if errExec != nil {
		err = xerrors.Errorf("sql=%s, args=%v: %w", sql, prms, errExec)
		return
	}
	cnt, err = result.RowsAffected()
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	dr.rowState = Deleted
	return
}
func (d daoDb受払仕入) DeleteW(wb Wb受払仕入) (cnt int64, err error) {
	where := wb.build()
	prms, exists := where.Params()
	if exists {
		sql := fmt.Sprintf(sqlDelete受払仕入, where.String())
		result, errExec := d.db.Exec(sql, prms...)
		if errExec != nil {
			err = xerrors.Errorf("sql=%s, args=%v: %w", sql, prms, errExec)
			return
		}
		cnt, err = result.RowsAffected()
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
	} else {
		result, errExec := d.db.Exec(sqlTruncate受払仕入)
		if errExec != nil {
			err = xerrors.Errorf("sql=%s: %w", sqlTruncate受払仕入, errExec)
			return
		}
		cnt, err = result.RowsAffected()
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
	}
	return
}
