// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

type tbl受払 string

func Tbl受払() tbl受払 {
	return tbl受払("受払")
}

type fld受払 string

func (t tbl受払) FldNo() fld受払 {
	return fld受払("No")
}
func (t tbl受払) Fld登録日時() fld受払 {
	return fld受払("登録日時")
}
func (t tbl受払) Fld計上月() fld受払 {
	return fld受払("計上月")
}
func (t tbl受払) Fld受払区分() fld受払 {
	return fld受払("受払区分")
}
func (t tbl受払) Fld赤伝フラグ() fld受払 {
	return fld受払("赤伝フラグ")
}
func (t tbl受払) Fld品目ID() fld受払 {
	return fld受払("品目ID")
}
func (t tbl受払) Fld基準数量() fld受払 {
	return fld受払("基準数量")
}
func (t tbl受払) Fld基準単位ID() fld受払 {
	return fld受払("基準単位ID")
}
