// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import "fmt"

type eb受払join受払仕入 struct {
	wb Wb受払仕入
}

func NewEb受払join受払仕入() *eb受払join受払仕入 {
	return &eb受払join受払仕入{wb: NewWb受払仕入()}
}
func (eb *eb受払join受払仕入) And(field fld受払仕入, op whereBuilderOperater, val interface{}) Eb受払 {
	eb.wb.And(field, op, val)
	return eb
}
func (eb *eb受払join受払仕入) buildEb受払(argCntStart ...int) (where Where) {
	where = eb.wb.build(argCntStart...)
	where.w = fmt.Sprintf(" AND EXISTS (SELECT * FROM \"受払_仕入\" WHERE \"受払_仕入\".\"No\" = \"受払\".\"No\" %s)", where.w)
	return
}
