// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import (
	decimal "github.com/shopspring/decimal"
	types "techbookfest16-sample/domain/types"
)

type Dto受払仕入 struct {
	FldNo     Id
	Fld仕入数量   decimal.Decimal
	Fld仕入単位ID types.Unit
	Fld仕入金額   decimal.Decimal
	Fld仕入通貨ID types.CurrencyUnit
	Fld仕入単価   decimal.Decimal

	rowState DataRowState
	Ub       *ub受払仕入 `json:"-"`
}

func (d Dto受払仕入) TableName() string {
	return "受払_仕入"
}
func (d Dto受払仕入) RowState() DataRowState {
	return d.rowState
}

// Import はDto受払仕入型に主キー以外を上書きする。
func (d *Dto受払仕入) Import(仕入数量 decimal.Decimal, 仕入単位ID types.Unit, 仕入金額 decimal.Decimal, 仕入通貨ID types.CurrencyUnit, 仕入単価 decimal.Decimal) {
	// 項目がすべて一致していたら、何もしない
	if d.Fld仕入数量 == 仕入数量 && d.Fld仕入単位ID == 仕入単位ID && d.Fld仕入金額 == 仕入金額 && d.Fld仕入通貨ID == 仕入通貨ID && d.Fld仕入単価 == 仕入単価 {
		return
	}
	if d.Fld仕入数量 != 仕入数量 {
		d.Fld仕入数量 = 仕入数量
		d.Ub.Set(Tbl受払仕入().Fld仕入数量(), 仕入数量)
	}
	if d.Fld仕入単位ID != 仕入単位ID {
		d.Fld仕入単位ID = 仕入単位ID
		d.Ub.Set(Tbl受払仕入().Fld仕入単位ID(), 仕入単位ID)
	}
	if d.Fld仕入金額 != 仕入金額 {
		d.Fld仕入金額 = 仕入金額
		d.Ub.Set(Tbl受払仕入().Fld仕入金額(), 仕入金額)
	}
	if d.Fld仕入通貨ID != 仕入通貨ID {
		d.Fld仕入通貨ID = 仕入通貨ID
		d.Ub.Set(Tbl受払仕入().Fld仕入通貨ID(), 仕入通貨ID)
	}
	if d.Fld仕入単価 != 仕入単価 {
		d.Fld仕入単価 = 仕入単価
		d.Ub.Set(Tbl受払仕入().Fld仕入単価(), 仕入単価)
	}

}
