// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

type tbl品目 string

func Tbl品目() tbl品目 {
	return tbl品目("品目")
}

type fld品目 string

func (t tbl品目) FldID() fld品目 {
	return fld品目("ID")
}
func (t tbl品目) Fldコード() fld品目 {
	return fld品目("コード")
}
func (t tbl品目) Fld名称() fld品目 {
	return fld品目("名称")
}
func (t tbl品目) Fld基準単位ID() fld品目 {
	return fld品目("基準単位ID")
}
func (t tbl品目) Fld生産用品目区分ID() fld品目 {
	return fld品目("生産用品目区分ID")
}
