// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import "fmt"

type eb品目join品目仕入品 struct {
	wb Wb品目仕入品
}

func NewEb品目join品目仕入品() *eb品目join品目仕入品 {
	return &eb品目join品目仕入品{wb: NewWb品目仕入品()}
}
func (eb *eb品目join品目仕入品) And(field fld品目仕入品, op whereBuilderOperater, val interface{}) Eb品目 {
	eb.wb.And(field, op, val)
	return eb
}
func (eb *eb品目join品目仕入品) buildEb品目(argCntStart ...int) (where Where) {
	where = eb.wb.build(argCntStart...)
	where.w = fmt.Sprintf(" AND EXISTS (SELECT * FROM \"品目_仕入品\" WHERE \"品目_仕入品\".\"ID\" = \"品目\".\"ID\" %s)", where.w)
	return
}
