// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import "fmt"

type eb品目join受払 struct {
	wb Wb受払
}

func NewEb品目join受払() *eb品目join受払 {
	return &eb品目join受払{wb: NewWb受払()}
}
func (eb *eb品目join受払) And(field fld受払, op whereBuilderOperater, val interface{}) Eb品目 {
	eb.wb.And(field, op, val)
	return eb
}
func (eb *eb品目join受払) buildEb品目(argCntStart ...int) (where Where) {
	where = eb.wb.build(argCntStart...)
	where.w = fmt.Sprintf(" AND EXISTS (SELECT * FROM \"受払\" WHERE \"受払\".\"品目ID\" = \"品目\".\"ID\" %s)", where.w)
	return
}
