// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

type tbl品目製造品 string

func Tbl品目製造品() tbl品目製造品 {
	return tbl品目製造品("品目_製造品")
}

type fld品目製造品 string

func (t tbl品目製造品) FldID() fld品目製造品 {
	return fld品目製造品("ID")
}
func (t tbl品目製造品) FldMRP計算対象フラグ() fld品目製造品 {
	return fld品目製造品("MRP計算対象フラグ")
}
