// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import (
	"database/sql"
	"fmt"
	a "github.com/Moiterika/a"
	xerrors "golang.org/x/xerrors"
	"strconv"
	"strings"
	types "techbookfest16-sample/domain/types"
)

type daoDb品目製造品 struct {
	dm        *DaoDbManager
	db        *sql.DB
	WbForInit Wb品目製造品
}

func (d *daoDb品目製造品) init() (err error) {
	d.dm.dt品目製造品, err = d.SelectW(d.WbForInit)
	if err != nil {
		return xerrors.Errorf(": %w", err)
	}
	d.dm.mapIDvsDr品目製造品 = a.ToMap(d.dm.dt品目製造品, func(e *Dto品目製造品) Id {
		return e.FldID
	})
	return
}
func (d *daoDb品目製造品) Reset() {
	list := make([]*Dto品目製造品, 0, len(d.dm.dt品目製造品))
	for _, dr := range d.dm.dt品目製造品 {
		if dr.rowState == Deleted {
			dr.rowState = Detached
			continue
		} else {
			dr.rowState = UnChanged
			list = append(list, dr)
		}
	}
	d.dm.dt品目製造品 = list
}
func (d daoDb品目製造品) Dt() ([]*Dto品目製造品, error) {
	if len(d.dm.dt品目製造品) == 0 {
		err := d.init()
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return nil, err
		}
	}
	return d.dm.dt品目製造品, nil
}
func (d daoDb品目製造品) GetBy(id Id) (dr *Dto品目製造品, err error) {
	if len(d.dm.mapIDvsDr品目製造品) == 0 {
		err = d.init()
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
	}
	var ok bool
	dr, ok = d.dm.mapIDvsDr品目製造品[id]
	if !ok {
		err = xerrors.Errorf("品目_製造品が見つかりません。ID=%d: %w", id, types.ErrNotFound)
		return
	}
	return
}
func (d daoDb品目製造品) SelectAll() ([]*Dto品目製造品, error) {
	sql := fmt.Sprintf(sqlSelect品目製造品, "")
	rows, err := d.db.Query(sql)
	if err != nil {
		return nil, xerrors.Errorf("sql=%s: %w", sql, err)
	}
	defer rows.Close()
	var dt []*Dto品目製造品
	for rows.Next() {
		var dr Dto品目製造品
		err = rows.Scan(&dr.FldID, &dr.FldMRP計算対象フラグ)
		if err != nil {
			return nil, xerrors.Errorf(": %w", err)
		}
		dr.rowState = Detached
		dr.Ub = NewUb品目製造品()
		dt = append(dt, &dr)
	}
	return dt, rows.Err()
}
func (d daoDb品目製造品) SelectW(wb Wb品目製造品) ([]*Dto品目製造品, error) {
	where := wb.build()
	prms, exists := where.Params()
	if exists {
		sql := fmt.Sprintf(sqlSelect品目製造品, where.String())
		rows, err := d.db.Query(sql, prms...)
		if err != nil {
			return nil, xerrors.Errorf("sql=%s, args=%v: %w", sql, prms, err)
		}
		defer rows.Close()
		var dt []*Dto品目製造品
		for rows.Next() {
			var dr Dto品目製造品
			err = rows.Scan(&dr.FldID, &dr.FldMRP計算対象フラグ)
			if err != nil {
				return nil, xerrors.Errorf(": %w", err)
			}
			dr.rowState = Detached
			dr.Ub = NewUb品目製造品()
			dt = append(dt, &dr)
		}
		return dt, rows.Err()
	} else {
		return d.SelectAll()
	}
}
func (d daoDb品目製造品) Count() (cnt int64, err error) {
	return d.CountW(NewWb品目製造品())
}
func (d daoDb品目製造品) CountW(wb Wb品目製造品) (cnt int64, err error) {
	where := wb.build()
	prms, exists := where.Params()
	if exists {
		err = d.db.QueryRow(fmt.Sprintf(sqlSelect品目製造品ForAggregation, "count(\"ID\")", where.String()), prms...).Scan(&cnt)
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
		return
	} else {
		err = d.db.QueryRow(fmt.Sprintf(sqlSelect品目製造品ForAggregation, "count(\"ID\")", "")).Scan(&cnt)
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
		return
	}
}

// Min は品目_製造品のfld最小値を返します。
func (d daoDb品目製造品) Min(fld fld品目製造品) (min int64, err error) {
	return d.MinW(fld, NewWb品目製造品())
}
func (d daoDb品目製造品) MinW(fld fld品目製造品, wb Wb品目製造品) (min int64, err error) {
	where := wb.build()
	prms, exists := where.Params()
	var x sql.NullInt64
	if exists {
		err = d.db.QueryRow(fmt.Sprintf(sqlSelect品目製造品ForAggregation, fmt.Sprintf("min(%s)", strconv.Quote(string(fld))), where.String()), prms...).Scan(&x)
	} else {
		err = d.db.QueryRow(fmt.Sprintf(sqlSelect品目製造品ForAggregation, fmt.Sprintf("min(%s)", strconv.Quote(string(fld))), where.String())).Scan(&x)
	}
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	if !x.Valid {
		err = xerrors.Errorf(": %w", types.ErrNotFound)
		return
	}
	min = x.Int64
	return
}

// Max は品目_製造品のfld最大値を返します。
func (d daoDb品目製造品) Max(fld fld品目製造品) (max int64, err error) {
	return d.MaxW(fld, NewWb品目製造品())
}
func (d daoDb品目製造品) MaxW(fld fld品目製造品, wb Wb品目製造品) (max int64, err error) {
	where := wb.build()
	prms, exists := where.Params()
	var x sql.NullInt64
	if exists {
		err = d.db.QueryRow(fmt.Sprintf(sqlSelect品目製造品ForAggregation, fmt.Sprintf("max(%s)", strconv.Quote(string(fld))), where.String()), prms...).Scan(&x)
	} else {
		err = d.db.QueryRow(fmt.Sprintf(sqlSelect品目製造品ForAggregation, fmt.Sprintf("max(%s)", strconv.Quote(string(fld))), where.String())).Scan(&x)
	}
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	if !x.Valid {
		err = xerrors.Errorf(": %w", types.ErrNotFound)
		return
	}
	max = x.Int64
	return
}
func (d daoDb品目製造品) Insert(dr *Dto品目製造品) (err error) {
	_, err = d.db.Exec(sqlInsert品目製造品, dr.FldID, dr.FldMRP計算対象フラグ)
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	dr.rowState = Added
	d.dm.dt品目製造品 = append(d.dm.dt品目製造品, dr)
	d.dm.mapIDvsDr品目製造品[dr.FldID] = dr
	return
}
func (d daoDb品目製造品) MultiInsert(dt []*Dto品目製造品) (err error) {
	cs := a.Chunk(dt, 1000)
	for _, c := range cs {
		vals := make([]string, len(c))
		args := make([]interface{}, len(c)*2)
		for i, dr := range c {
			vals[i] = fmt.Sprintf(sqlValue2, 2*i+1, 2*i+2)
			args[2*i] = dr.FldID
			args[2*i+1] = dr.FldMRP計算対象フラグ
			dr.rowState = Added
		}
		_, err = d.db.Exec(fmt.Sprintf(sqlMultiInsert品目製造品, strings.Join(vals, ",")), args...)
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
	}
	return
}
func (d daoDb品目製造品) UpdateBy(dr *Dto品目製造品) (cnt int64, err error) {
	if dr.Ub.Count() == 0 {
		dr.rowState = UnChanged
		return
	}
	s, w, execArgs := dr.Ub.build(newWb品目製造品WithPrimaryKeys(dr.FldID))
	sql := fmt.Sprintf(sqlUpdate品目製造品, s, w)
	result, err := d.db.Exec(sql, execArgs...)
	if err != nil {
		err = xerrors.Errorf("sql=%s, args=%v: %w", sql, execArgs, err)
		return
	}
	cnt, err = result.RowsAffected()
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	dr.rowState = Modified
	return
}
func (d daoDb品目製造品) UpdateW(ub *ub品目製造品, wb Wb品目製造品) (cnt int64, err error) {
	s, w, execArgs := ub.build(wb)
	sql := fmt.Sprintf(sqlUpdate品目製造品, s, w)
	result, err := d.db.Exec(sql, execArgs...)
	if err != nil {
		err = xerrors.Errorf("sql=%s, args=%v: %w", sql, execArgs, err)
		return
	}
	cnt, err = result.RowsAffected()
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	return
}
func (d daoDb品目製造品) DeleteBy(dr *Dto品目製造品) (cnt int64, err error) {
	where := newWb品目製造品WithPrimaryKeys(dr.FldID).build()
	prms, exists := where.Params()
	if !exists {
		err = xerrors.Errorf("主キーがありません。: %#v", *dr)
		return
	}
	sql := fmt.Sprintf(sqlDelete品目製造品, where.String())
	result, errExec := d.db.Exec(sql, prms...)
	if errExec != nil {
		err = xerrors.Errorf("sql=%s, args=%v: %w", sql, prms, errExec)
		return
	}
	cnt, err = result.RowsAffected()
	if err != nil {
		err = xerrors.Errorf(": %w", err)
		return
	}
	dr.rowState = Deleted
	return
}
func (d daoDb品目製造品) DeleteW(wb Wb品目製造品) (cnt int64, err error) {
	where := wb.build()
	prms, exists := where.Params()
	if exists {
		sql := fmt.Sprintf(sqlDelete品目製造品, where.String())
		result, errExec := d.db.Exec(sql, prms...)
		if errExec != nil {
			err = xerrors.Errorf("sql=%s, args=%v: %w", sql, prms, errExec)
			return
		}
		cnt, err = result.RowsAffected()
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
	} else {
		result, errExec := d.db.Exec(sqlTruncate品目製造品)
		if errExec != nil {
			err = xerrors.Errorf("sql=%s: %w", sqlTruncate品目製造品, errExec)
			return
		}
		cnt, err = result.RowsAffected()
		if err != nil {
			err = xerrors.Errorf(": %w", err)
			return
		}
	}
	return
}
