// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

type tbl品目仕入品 string

func Tbl品目仕入品() tbl品目仕入品 {
	return tbl品目仕入品("品目_仕入品")
}

type fld品目仕入品 string

func (t tbl品目仕入品) FldID() fld品目仕入品 {
	return fld品目仕入品("ID")
}
func (t tbl品目仕入品) Fld標準単価() fld品目仕入品 {
	return fld品目仕入品("標準単価")
}
func (t tbl品目仕入品) Fld標準単価通貨ID() fld品目仕入品 {
	return fld品目仕入品("標準単価通貨ID")
}
func (t tbl品目仕入品) Fld標準単価単位ID() fld品目仕入品 {
	return fld品目仕入品("標準単価単位ID")
}
