// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import "fmt"

type eb品目製造品join品目 struct {
	wb Wb品目
}

func NewEb品目製造品join品目() *eb品目製造品join品目 {
	return &eb品目製造品join品目{wb: NewWb品目()}
}
func (eb *eb品目製造品join品目) And(field fld品目, op whereBuilderOperater, val interface{}) Eb品目製造品 {
	eb.wb.And(field, op, val)
	return eb
}
func (eb *eb品目製造品join品目) buildEb品目製造品(argCntStart ...int) (where Where) {
	where = eb.wb.build(argCntStart...)
	where.w = fmt.Sprintf(" AND EXISTS (SELECT * FROM \"品目\" WHERE \"品目\".\"ID\" = \"品目_製造品\".\"ID\" %s)", where.w)
	return
}
