// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

type tbl生産用品目区分 string

func Tbl生産用品目区分() tbl生産用品目区分 {
	return tbl生産用品目区分("生産用品目区分")
}

type fld生産用品目区分 string

func (t tbl生産用品目区分) FldID() fld生産用品目区分 {
	return fld生産用品目区分("ID")
}
func (t tbl生産用品目区分) Fldコード() fld生産用品目区分 {
	return fld生産用品目区分("コード")
}
func (t tbl生産用品目区分) Fld名称() fld生産用品目区分 {
	return fld生産用品目区分("名称")
}
func (t tbl生産用品目区分) Fld何かのフラグ1() fld生産用品目区分 {
	return fld生産用品目区分("何かのフラグ1")
}
func (t tbl生産用品目区分) Fld何かのフラグ2() fld生産用品目区分 {
	return fld生産用品目区分("何かのフラグ2")
}
