// Code generated by xlsx2go.go; DO NOT EDIT.

package dao

import "fmt"

type eb生産用品目区分join品目 struct {
	wb Wb品目
}

func NewEb生産用品目区分join品目() *eb生産用品目区分join品目 {
	return &eb生産用品目区分join品目{wb: NewWb品目()}
}
func (eb *eb生産用品目区分join品目) And(field fld品目, op whereBuilderOperater, val interface{}) Eb生産用品目区分 {
	eb.wb.And(field, op, val)
	return eb
}
func (eb *eb生産用品目区分join品目) buildEb生産用品目区分(argCntStart ...int) (where Where) {
	where = eb.wb.build(argCntStart...)
	where.w = fmt.Sprintf(" AND EXISTS (SELECT * FROM \"品目\" WHERE \"品目\".\"生産用品目区分ID\" = \"生産用品目区分\".\"ID\" %s)", where.w)
	return
}
